//! Every numeric constant of the merged WEB source (`@d x=...`), in source
//! order. Generated by `scripts/gen-webconsts.py`; do not edit by hand.
//! The section comments are where tex.web (or else pdftex.web) defines each
//! name; values are pdfTeX's, whose layout is a superset of TeX's.

#![allow(
    dead_code,
    unused_parens,
    clippy::identity_op,
    clippy::eq_op,
    clippy::double_parens
)]

/// pdfTeX §2
pub const ETEX_VERSION: i32 = 2;
/// pdfTeX §2
pub const PDFTEX_VERSION: i32 = 140;
/// pdfTeX §2
pub const TEXXET_CODE: i32 = 0;
/// `XeTeX` §2
pub const ETEX_STATES: i32 = 12;
/// §6
pub const START_OF_TEX: i32 = 1;
/// §6
pub const FINAL_END: i32 = 9999;
/// §11
pub const SSUP_ERROR_LINE: i32 = 255;
/// §11
pub const SSUP_MAX_STRINGS: i32 = 2097151;
/// §11
pub const SSUP_TRIE_OPCODE: i32 = 65535;
/// §11
pub const SSUP_TRIE_SIZE: i32 = 0x3fffff;
/// §11
pub const SSUP_HYPH_SIZE: i32 = 65535;
/// §11
pub const IINF_HYPHEN_SIZE: i32 = 610;
/// §11
pub const MAX_FONT_MAX: i32 = 9000;
/// §11
pub const FONT_BASE: i32 = 0;
/// §12
pub const HASH_SIZE: i32 = 15000;
/// §12
pub const HASH_PRIME: i32 = 8501;
/// §12
pub const HYPH_PRIME: i32 = 607;
/// §15
pub const EXIT: i32 = 10;
/// §15
pub const RESTART: i32 = 20;
/// §15
pub const RESWITCH: i32 = 21;
/// §15
pub const CONTINUE: i32 = 22;
/// §15
pub const DONE: i32 = 30;
/// §15
pub const DONE1: i32 = 31;
/// §15
pub const DONE2: i32 = 32;
/// §15
pub const DONE3: i32 = 33;
/// §15
pub const DONE4: i32 = 34;
/// §15
pub const DONE5: i32 = 35;
/// §15
pub const DONE6: i32 = 36;
/// §15
pub const FOUND: i32 = 40;
/// §15
pub const FOUND1: i32 = 41;
/// §15
pub const FOUND2: i32 = 42;
/// §15
pub const NOT_FOUND: i32 = 45;
/// pdfTeX §15
pub const NOT_FOUND1: i32 = 46;
/// pdfTeX §15
pub const NOT_FOUND2: i32 = 47;
/// pdfTeX §15
pub const NOT_FOUND3: i32 = 48;
/// pdfTeX §15
pub const NOT_FOUND4: i32 = 49;
/// §15
pub const COMMON_ENDING: i32 = 50;
/// §16
pub const EMPTY: i32 = 0;
/// §19
pub const FIRST_TEXT_CHAR: i32 = 0;
/// §19
pub const LAST_TEXT_CHAR: i32 = 255;
/// §22
pub const NULL_CODE: i32 = 0o0;
/// §22
pub const CARRIAGE_RETURN: i32 = 0o15;
/// §22
pub const INVALID_CODE: i32 = 0o177;
/// §54
pub const NO_PRINT: i32 = 16;
/// §54
pub const TERM_ONLY: i32 = 17;
/// §54
pub const LOG_ONLY: i32 = 18;
/// §54
pub const TERM_AND_LOG: i32 = 19;
/// §54
pub const PSEUDO: i32 = 20;
/// §54
pub const NEW_STRING: i32 = 21;
/// §54
pub const MAX_SELECTOR: i32 = 21;
/// §73
pub const BATCH_MODE: i32 = 0;
/// §73
pub const NONSTOP_MODE: i32 = 1;
/// §73
pub const SCROLL_MODE: i32 = 2;
/// §73
pub const ERROR_STOP_MODE: i32 = 3;
/// §73
pub const UNSPECIFIED_MODE: i32 = 4;
/// §76
pub const SPOTLESS: i32 = 0;
/// §76
pub const WARNING_ISSUED: i32 = 1;
/// §76
pub const ERROR_MESSAGE_ISSUED: i32 = 2;
/// §76
pub const FATAL_ERROR_STOP: i32 = 3;
/// §101
pub const UNITY: i32 = 0o200000;
/// §101
pub const TWO: i32 = 0o400000;
/// §108
pub const INF_BAD: i32 = 10000;
/// pdfTeX §111
pub const FRACTION_HALF: i32 = 0o1000000000;
/// pdfTeX §111
pub const FRACTION_ONE: i32 = 0o2000000000;
/// pdfTeX §111
pub const FRACTION_FOUR: i32 = 0o10000000000;
/// pdfTeX §111
pub const EL_GORDO: i32 = 0o17777777777;
/// §110
pub const MIN_QUARTERWORD: i32 = 0;
/// §110
pub const MAX_QUARTERWORD: i32 = 255;
/// §110
pub const MIN_HALFWORD: i32 = -0xfffffff;
/// §110
pub const MAX_HALFWORD: i32 = 0xfffffff;
/// §115
pub const NULL: i32 = MIN_HALFWORD;
/// §124
pub const EMPTY_FLAG: i32 = MAX_HALFWORD;
/// pdfTeX §153
pub const SYNCTEX_FIELD_SIZE: i32 = 2;
/// §135
pub const HLIST_NODE: i32 = 0;
/// §135
pub const BOX_NODE_SIZE: i32 = 7 + SYNCTEX_FIELD_SIZE;
/// §135
pub const WIDTH_OFFSET: i32 = 1;
/// §135
pub const DEPTH_OFFSET: i32 = 2;
/// §135
pub const HEIGHT_OFFSET: i32 = 3;
/// §135
pub const LIST_OFFSET: i32 = 5;
/// §135
pub const NORMAL: i32 = 0;
/// §135
pub const STRETCHING: i32 = 1;
/// §135
pub const SHRINKING: i32 = 2;
/// §135
pub const GLUE_OFFSET: i32 = 6;
/// §137
pub const VLIST_NODE: i32 = 1;
/// §138
pub const RULE_NODE: i32 = 2;
/// §138
pub const RULE_NODE_SIZE: i32 = 4 + SYNCTEX_FIELD_SIZE;
/// §138
pub const NULL_FLAG: i32 = -0o10000000000;
/// §140
pub const INS_NODE: i32 = 3;
/// §140
pub const INS_NODE_SIZE: i32 = 5;
/// §141
pub const MARK_NODE: i32 = 4;
/// §141
pub const SMALL_NODE_SIZE: i32 = 2;
/// pdfTeX §159
pub const MEDIUM_NODE_SIZE: i32 = SMALL_NODE_SIZE + SYNCTEX_FIELD_SIZE;
/// §142
pub const ADJUST_NODE: i32 = 5;
/// §143
pub const LIGATURE_NODE: i32 = 6;
/// §145
pub const DISC_NODE: i32 = 7;
/// §146
pub const WHATSIT_NODE: i32 = 8;
/// §147
pub const MATH_NODE: i32 = 9;
/// §147
pub const BEFORE: i32 = 0;
/// §147
pub const AFTER: i32 = 1;
/// pdfTeX §165
pub const M_CODE: i32 = 2;
/// pdfTeX §165
pub const BEGIN_M_CODE: i32 = M_CODE + BEFORE;
/// pdfTeX §165
pub const END_M_CODE: i32 = M_CODE + AFTER;
/// pdfTeX §165
pub const L_CODE: i32 = 4;
/// pdfTeX §165
pub const BEGIN_L_CODE: i32 = L_CODE + BEGIN_M_CODE;
/// pdfTeX §165
pub const END_L_CODE: i32 = L_CODE + END_M_CODE;
/// pdfTeX §165
pub const R_CODE: i32 = L_CODE + L_CODE;
/// pdfTeX §165
pub const BEGIN_R_CODE: i32 = R_CODE + BEGIN_M_CODE;
/// pdfTeX §165
pub const END_R_CODE: i32 = R_CODE + END_M_CODE;
/// §149
pub const GLUE_NODE: i32 = 10;
/// §149
pub const COND_MATH_GLUE: i32 = 98;
/// §149
pub const MU_GLUE: i32 = 99;
/// §149
pub const A_LEADERS: i32 = 100;
/// §149
pub const C_LEADERS: i32 = 101;
/// §149
pub const X_LEADERS: i32 = 102;
/// §150
pub const GLUE_SPEC_SIZE: i32 = 4;
/// §150
pub const FIL: i32 = 1;
/// §150
pub const FILL: i32 = 2;
/// §150
pub const FILLL: i32 = 3;
/// §155
pub const KERN_NODE: i32 = 11;
/// §155
pub const EXPLICIT: i32 = 1;
/// §155
pub const ACC_KERN: i32 = 2;
/// pdfTeX §173
pub const AUTO_KERN: i32 = 3;
/// pdfTeX §173
pub const MARGIN_KERN_NODE: i32 = 40;
/// pdfTeX §173
pub const MARGIN_KERN_NODE_SIZE: i32 = 3;
/// pdfTeX §173
pub const LEFT_SIDE: i32 = 0;
/// pdfTeX §173
pub const RIGHT_SIDE: i32 = 1;
/// pdfTeX §173
pub const LP_CODE_BASE: i32 = 2;
/// pdfTeX §173
pub const RP_CODE_BASE: i32 = 3;
/// pdfTeX §173
pub const EF_CODE_BASE: i32 = 4;
/// pdfTeX §173
pub const TAG_CODE: i32 = 5;
/// pdfTeX §173
pub const KN_BS_CODE_BASE: i32 = 7;
/// pdfTeX §173
pub const ST_BS_CODE_BASE: i32 = 8;
/// pdfTeX §173
pub const SH_BS_CODE_BASE: i32 = 9;
/// pdfTeX §173
pub const KN_BC_CODE_BASE: i32 = 10;
/// pdfTeX §173
pub const KN_AC_CODE_BASE: i32 = 11;
/// pdfTeX §173
pub const NO_LIG_CODE: i32 = 6;
/// pdfTeX §173
pub const MAX_HLIST_STACK: i32 = 512;
/// §157
pub const PENALTY_NODE: i32 = 12;
/// §157
pub const INF_PENALTY: i32 = INF_BAD;
/// §157
pub const EJECT_PENALTY: i32 = -INF_PENALTY;
/// §159
pub const UNSET_NODE: i32 = 13;
/// §162
pub const HI_MEM_STAT_USAGE: i32 = 15;
/// §207
pub const ESCAPE: i32 = 0;
/// §207
pub const RELAX: i32 = 0;
/// §207
pub const LEFT_BRACE: i32 = 1;
/// §207
pub const RIGHT_BRACE: i32 = 2;
/// §207
pub const MATH_SHIFT: i32 = 3;
/// §207
pub const TAB_MARK: i32 = 4;
/// §207
pub const CAR_RET: i32 = 5;
/// §207
pub const OUT_PARAM: i32 = 5;
/// §207
pub const MAC_PARAM: i32 = 6;
/// §207
pub const SUP_MARK: i32 = 7;
/// §207
pub const SUB_MARK: i32 = 8;
/// §207
pub const IGNORE: i32 = 9;
/// §207
pub const ENDV: i32 = 9;
/// §207
pub const SPACER: i32 = 10;
/// §207
pub const LETTER: i32 = 11;
/// §207
pub const OTHER_CHAR: i32 = 12;
/// §207
pub const ACTIVE_CHAR: i32 = 13;
/// §207
pub const PAR_END: i32 = 13;
/// §207
pub const MATCH: i32 = 13;
/// §207
pub const COMMENT: i32 = 14;
/// §207
pub const END_MATCH: i32 = 14;
/// §207
pub const STOP: i32 = 14;
/// §207
pub const INVALID_CHAR: i32 = 15;
/// §207
pub const DELIM_NUM: i32 = 15;
/// §207
pub const MAX_CHAR_CODE: i32 = 15;
/// §208
pub const CHAR_NUM: i32 = 16;
/// §208
pub const MATH_CHAR_NUM: i32 = 17;
/// §208
pub const MARK: i32 = 18;
/// §208
pub const XRAY: i32 = 19;
/// §208
pub const MAKE_BOX: i32 = 20;
/// §208
pub const HMOVE: i32 = 21;
/// §208
pub const VMOVE: i32 = 22;
/// §208
pub const UN_HBOX: i32 = 23;
/// §208
pub const UN_VBOX: i32 = 24;
/// §208
pub const REMOVE_ITEM: i32 = 25;
/// §208
pub const HSKIP: i32 = 26;
/// §208
pub const VSKIP: i32 = 27;
/// §208
pub const MSKIP: i32 = 28;
/// §208
pub const KERN: i32 = 29;
/// §208
pub const MKERN: i32 = 30;
/// §208
pub const LEADER_SHIP: i32 = 31;
/// §208
pub const HALIGN: i32 = 32;
/// §208
pub const VALIGN: i32 = 33;
/// §208
pub const NO_ALIGN: i32 = 34;
/// §208
pub const VRULE: i32 = 35;
/// §208
pub const HRULE: i32 = 36;
/// §208
pub const INSERT: i32 = 37;
/// §208
pub const VADJUST: i32 = 38;
/// §208
pub const IGNORE_SPACES: i32 = 39;
/// §208
pub const AFTER_ASSIGNMENT: i32 = 40;
/// §208
pub const AFTER_GROUP: i32 = 41;
/// §208
pub const BREAK_PENALTY: i32 = 42;
/// §208
pub const START_PAR: i32 = 43;
/// §208
pub const ITAL_CORR: i32 = 44;
/// §208
pub const ACCENT: i32 = 45;
/// §208
pub const MATH_ACCENT: i32 = 46;
/// §208
pub const DISCRETIONARY: i32 = 47;
/// §208
pub const EQ_NO: i32 = 48;
/// §208
pub const LEFT_RIGHT: i32 = 49;
/// §208
pub const MATH_COMP: i32 = 50;
/// §208
pub const LIMIT_SWITCH: i32 = 51;
/// §208
pub const ABOVE: i32 = 52;
/// §208
pub const MATH_STYLE: i32 = 53;
/// §208
pub const MATH_CHOICE: i32 = 54;
/// §208
pub const NON_SCRIPT: i32 = 55;
/// §208
pub const VCENTER: i32 = 56;
/// §208
pub const CASE_SHIFT: i32 = 57;
/// §208
pub const MESSAGE: i32 = 58;
/// §208
pub const EXTENSION: i32 = 59;
/// §208
pub const IN_STREAM: i32 = 60;
/// §208
pub const BEGIN_GROUP: i32 = 61;
/// §208
pub const END_GROUP: i32 = 62;
/// §208
pub const OMIT: i32 = 63;
/// §208
pub const EX_SPACE: i32 = 64;
/// §208
pub const NO_BOUNDARY: i32 = 65;
/// §208
pub const RADICAL: i32 = 66;
/// §208
pub const END_CS_NAME: i32 = 67;
/// §208
pub const MIN_INTERNAL: i32 = 68;
/// §208
pub const CHAR_GIVEN: i32 = 68;
/// §208
pub const MATH_GIVEN: i32 = 69;
/// `XeTeX` §234
pub const LAST_ITEM: i32 = 71;
/// `XeTeX` §234
pub const MAX_NON_PREFIXED_COMMAND: i32 = 71;
/// `XeTeX` §235
pub const TOKS_REGISTER: i32 = 72;
/// `XeTeX` §235
pub const ASSIGN_TOKS: i32 = 73;
/// `XeTeX` §235
pub const ASSIGN_INT: i32 = 74;
/// `XeTeX` §235
pub const ASSIGN_DIMEN: i32 = 75;
/// `XeTeX` §235
pub const ASSIGN_GLUE: i32 = 76;
/// `XeTeX` §235
pub const ASSIGN_MU_GLUE: i32 = 77;
/// `XeTeX` §235
pub const ASSIGN_FONT_DIMEN: i32 = 78;
/// `XeTeX` §235
pub const ASSIGN_FONT_INT: i32 = 79;
/// `XeTeX` §235
pub const SET_AUX: i32 = 80;
/// `XeTeX` §235
pub const SET_PREV_GRAF: i32 = 81;
/// `XeTeX` §235
pub const SET_PAGE_DIMEN: i32 = 82;
/// `XeTeX` §235
pub const SET_PAGE_INT: i32 = 83;
/// `XeTeX` §235
pub const SET_BOX_DIMEN: i32 = 84;
/// `XeTeX` §235
pub const SET_SHAPE: i32 = 85;
/// `XeTeX` §235
pub const DEF_CODE: i32 = 86;
/// `XeTeX` §235
pub const DEF_FAMILY: i32 = 88;
/// `XeTeX` §235
pub const SET_FONT: i32 = 89;
/// `XeTeX` §235
pub const DEF_FONT: i32 = 90;
/// `XeTeX` §235
pub const REGISTER: i32 = 91;
/// `XeTeX` §235
pub const MAX_INTERNAL: i32 = 91;
/// `XeTeX` §235
pub const ADVANCE: i32 = 92;
/// `XeTeX` §235
pub const MULTIPLY: i32 = 93;
/// `XeTeX` §235
pub const DIVIDE: i32 = 94;
/// `XeTeX` §235
pub const PREFIX: i32 = 95;
/// `XeTeX` §235
pub const LET: i32 = 96;
/// `XeTeX` §235
pub const SHORTHAND_DEF: i32 = 97;
/// `XeTeX` §235
pub const READ_TO_CS: i32 = 98;
/// `XeTeX` §235
pub const DEF: i32 = 99;
/// `XeTeX` §235
pub const SET_BOX: i32 = 100;
/// `XeTeX` §235
pub const HYPH_DATA: i32 = 101;
/// `XeTeX` §235
pub const SET_INTERACTION: i32 = 102;
/// pdfTeX §227
pub const LETTERSPACE_FONT: i32 = SET_INTERACTION + 1;
/// pdfTeX §227
pub const PDF_COPY_FONT: i32 = SET_INTERACTION + 2;
/// `XeTeX` §235
pub const PARTOKEN_NAME: i32 = SET_INTERACTION + 3;
/// `XeTeX` §235
pub const MAX_COMMAND: i32 = SET_INTERACTION + 3;
/// §210
pub const UNDEFINED_CS: i32 = MAX_COMMAND + 1;
/// §210
pub const EXPAND_AFTER: i32 = MAX_COMMAND + 2;
/// §210
pub const NO_EXPAND: i32 = MAX_COMMAND + 3;
/// §210
pub const INPUT: i32 = MAX_COMMAND + 4;
/// §210
pub const IF_TEST: i32 = MAX_COMMAND + 5;
/// §210
pub const FI_OR_ELSE: i32 = MAX_COMMAND + 6;
/// §210
pub const CS_NAME: i32 = MAX_COMMAND + 7;
/// §210
pub const CONVERT: i32 = MAX_COMMAND + 8;
/// §210
pub const THE: i32 = MAX_COMMAND + 9;
/// §210
pub const TOP_BOT_MARK: i32 = MAX_COMMAND + 10;
/// §210
pub const CALL: i32 = MAX_COMMAND + 11;
/// §210
pub const LONG_CALL: i32 = MAX_COMMAND + 12;
/// §210
pub const OUTER_CALL: i32 = MAX_COMMAND + 13;
/// §210
pub const LONG_OUTER_CALL: i32 = MAX_COMMAND + 14;
/// §210
pub const END_TEMPLATE: i32 = MAX_COMMAND + 15;
/// §210
pub const DONT_EXPAND: i32 = MAX_COMMAND + 16;
/// §210
pub const GLUE_REF: i32 = MAX_COMMAND + 17;
/// §210
pub const SHAPE_REF: i32 = MAX_COMMAND + 18;
/// §210
pub const BOX_REF: i32 = MAX_COMMAND + 19;
/// §210
pub const DATA: i32 = MAX_COMMAND + 20;
/// §211
pub const VMODE: i32 = 1;
/// §211
pub const HMODE: i32 = VMODE + MAX_COMMAND + 1;
/// §211
pub const MMODE: i32 = HMODE + MAX_COMMAND + 1;
/// §212
pub const IGNORE_DEPTH: i32 = -65536000;
/// §221
pub const LEVEL_ZERO: i32 = MIN_QUARTERWORD;
/// §221
pub const LEVEL_ONE: i32 = LEVEL_ZERO + 1;
/// §222
pub const ACTIVE_BASE: i32 = 1;
/// §222
pub const SINGLE_BASE: i32 = ACTIVE_BASE + 256;
/// §222
pub const NULL_CS: i32 = SINGLE_BASE + 256;
/// §222
pub const HASH_BASE: i32 = NULL_CS + 1;
/// §222
pub const FROZEN_CONTROL_SEQUENCE: i32 = HASH_BASE + HASH_SIZE;
/// §222
pub const FROZEN_PROTECTION: i32 = FROZEN_CONTROL_SEQUENCE;
/// §222
pub const FROZEN_CR: i32 = FROZEN_CONTROL_SEQUENCE + 1;
/// §222
pub const FROZEN_END_GROUP: i32 = FROZEN_CONTROL_SEQUENCE + 2;
/// §222
pub const FROZEN_RIGHT: i32 = FROZEN_CONTROL_SEQUENCE + 3;
/// §222
pub const FROZEN_FI: i32 = FROZEN_CONTROL_SEQUENCE + 4;
/// §222
pub const FROZEN_END_TEMPLATE: i32 = FROZEN_CONTROL_SEQUENCE + 5;
/// §222
pub const FROZEN_ENDV: i32 = FROZEN_CONTROL_SEQUENCE + 6;
/// §222
pub const FROZEN_RELAX: i32 = FROZEN_CONTROL_SEQUENCE + 7;
/// §222
pub const END_WRITE: i32 = FROZEN_CONTROL_SEQUENCE + 8;
/// §222
pub const FROZEN_DONT_EXPAND: i32 = FROZEN_CONTROL_SEQUENCE + 9;
/// pdfTeX §240
pub const PRIM_SIZE: i32 = 2100;
/// §222
pub const FROZEN_SPECIAL: i32 = FROZEN_CONTROL_SEQUENCE + 10;
/// §222
pub const FROZEN_NULL_FONT: i32 = FROZEN_CONTROL_SEQUENCE + 12 + PRIM_SIZE;
/// pdfTeX §240
pub const FROZEN_PRIMITIVE: i32 = FROZEN_CONTROL_SEQUENCE + 11;
/// pdfTeX §240
pub const PRIM_EQTB_BASE: i32 = FROZEN_PRIMITIVE + 1;
/// §222
pub const FONT_ID_BASE: i32 = FROZEN_NULL_FONT - FONT_BASE;
/// §222
pub const UNDEFINED_CONTROL_SEQUENCE: i32 = FROZEN_NULL_FONT + MAX_FONT_MAX + 1;
/// §222
pub const GLUE_BASE: i32 = UNDEFINED_CONTROL_SEQUENCE + 1;
/// §224
pub const LINE_SKIP_CODE: i32 = 0;
/// §224
pub const BASELINE_SKIP_CODE: i32 = 1;
/// §224
pub const PAR_SKIP_CODE: i32 = 2;
/// §224
pub const ABOVE_DISPLAY_SKIP_CODE: i32 = 3;
/// §224
pub const BELOW_DISPLAY_SKIP_CODE: i32 = 4;
/// §224
pub const ABOVE_DISPLAY_SHORT_SKIP_CODE: i32 = 5;
/// §224
pub const BELOW_DISPLAY_SHORT_SKIP_CODE: i32 = 6;
/// §224
pub const LEFT_SKIP_CODE: i32 = 7;
/// §224
pub const RIGHT_SKIP_CODE: i32 = 8;
/// §224
pub const TOP_SKIP_CODE: i32 = 9;
/// §224
pub const SPLIT_TOP_SKIP_CODE: i32 = 10;
/// §224
pub const TAB_SKIP_CODE: i32 = 11;
/// §224
pub const SPACE_SKIP_CODE: i32 = 12;
/// §224
pub const XSPACE_SKIP_CODE: i32 = 13;
/// §224
pub const PAR_FILL_SKIP_CODE: i32 = 14;
/// `XeTeX` §250
pub const THIN_MU_SKIP_CODE: i32 = 16;
/// `XeTeX` §250
pub const MED_MU_SKIP_CODE: i32 = 17;
/// `XeTeX` §250
pub const THICK_MU_SKIP_CODE: i32 = 18;
/// `XeTeX` §250
pub const GLUE_PARS: i32 = 19;
/// §224
pub const SKIP_BASE: i32 = GLUE_BASE + GLUE_PARS;
/// §224
pub const MU_SKIP_BASE: i32 = SKIP_BASE + 256;
/// §224
pub const LOCAL_BASE: i32 = MU_SKIP_BASE + 256;
/// §230
pub const PAR_SHAPE_LOC: i32 = LOCAL_BASE;
/// §230
pub const OUTPUT_ROUTINE_LOC: i32 = LOCAL_BASE + 1;
/// §230
pub const EVERY_PAR_LOC: i32 = LOCAL_BASE + 2;
/// §230
pub const EVERY_MATH_LOC: i32 = LOCAL_BASE + 3;
/// §230
pub const EVERY_DISPLAY_LOC: i32 = LOCAL_BASE + 4;
/// §230
pub const EVERY_HBOX_LOC: i32 = LOCAL_BASE + 5;
/// §230
pub const EVERY_VBOX_LOC: i32 = LOCAL_BASE + 6;
/// §230
pub const EVERY_JOB_LOC: i32 = LOCAL_BASE + 7;
/// §230
pub const EVERY_CR_LOC: i32 = LOCAL_BASE + 8;
/// §230
pub const ERR_HELP_LOC: i32 = LOCAL_BASE + 9;
/// pdfTeX §248
pub const TEX_TOKS: i32 = LOCAL_BASE + 10;
/// pdfTeX §248
pub const PDFTEX_FIRST_LOC: i32 = TEX_TOKS;
/// pdfTeX §248
pub const PDF_PAGES_ATTR_LOC: i32 = PDFTEX_FIRST_LOC + 0;
/// pdfTeX §248
pub const PDF_PAGE_ATTR_LOC: i32 = PDFTEX_FIRST_LOC + 1;
/// pdfTeX §248
pub const PDF_PAGE_RESOURCES_LOC: i32 = PDFTEX_FIRST_LOC + 2;
/// pdfTeX §248
pub const PDF_PK_MODE_LOC: i32 = PDFTEX_FIRST_LOC + 3;
/// pdfTeX §248
pub const PDF_TOKS: i32 = PDFTEX_FIRST_LOC + 4;
/// pdfTeX §248
pub const ETEX_TOKS_BASE: i32 = PDF_TOKS;
/// pdfTeX §248
pub const EVERY_EOF_LOC: i32 = ETEX_TOKS_BASE;
/// `XeTeX` §256
pub const ETEX_TOKS: i32 = XETEX_INTER_CHAR_LOC + 1;
/// §230
pub const TOKS_BASE: i32 = ETEX_TOKS;
/// pdfTeX §248
pub const ETEX_PEN_BASE: i32 = TOKS_BASE + 256;
/// pdfTeX §248
pub const INTER_LINE_PENALTIES_LOC: i32 = ETEX_PEN_BASE;
/// pdfTeX §248
pub const CLUB_PENALTIES_LOC: i32 = ETEX_PEN_BASE + 1;
/// pdfTeX §248
pub const WIDOW_PENALTIES_LOC: i32 = ETEX_PEN_BASE + 2;
/// pdfTeX §248
pub const DISPLAY_WIDOW_PENALTIES_LOC: i32 = ETEX_PEN_BASE + 3;
/// pdfTeX §248
pub const ETEX_PENS: i32 = ETEX_PEN_BASE + 4;
/// §230
pub const BOX_BASE: i32 = ETEX_PENS;
/// §230
pub const CUR_FONT_LOC: i32 = BOX_BASE + 256;
/// §230
pub const XORD_CODE_BASE: i32 = CUR_FONT_LOC + 1;
/// §230
pub const XCHR_CODE_BASE: i32 = XORD_CODE_BASE + 1;
/// §230
pub const XPRN_CODE_BASE: i32 = XCHR_CODE_BASE + 1;
/// §230
pub const MATH_FONT_BASE: i32 = XPRN_CODE_BASE + 1;
/// `XeTeX` §256
pub const CAT_CODE_BASE: i32 = MATH_FONT_BASE + NUMBER_MATH_FONTS;
/// §230
pub const LC_CODE_BASE: i32 = CAT_CODE_BASE + 256;
/// §230
pub const UC_CODE_BASE: i32 = LC_CODE_BASE + 256;
/// §230
pub const SF_CODE_BASE: i32 = UC_CODE_BASE + 256;
/// §230
pub const MATH_CODE_BASE: i32 = SF_CODE_BASE + 256;
/// §230
pub const CHAR_SUB_CODE_BASE: i32 = MATH_CODE_BASE + 256;
/// §230
pub const INT_BASE: i32 = CHAR_SUB_CODE_BASE + 256;
/// §232
pub const NULL_FONT: i32 = FONT_BASE;
/// §232
pub const VAR_CODE: i32 = 0o70000;
/// §236
pub const PRETOLERANCE_CODE: i32 = 0;
/// §236
pub const TOLERANCE_CODE: i32 = 1;
/// §236
pub const LINE_PENALTY_CODE: i32 = 2;
/// §236
pub const HYPHEN_PENALTY_CODE: i32 = 3;
/// §236
pub const EX_HYPHEN_PENALTY_CODE: i32 = 4;
/// §236
pub const CLUB_PENALTY_CODE: i32 = 5;
/// §236
pub const WIDOW_PENALTY_CODE: i32 = 6;
/// §236
pub const DISPLAY_WIDOW_PENALTY_CODE: i32 = 7;
/// §236
pub const BROKEN_PENALTY_CODE: i32 = 8;
/// §236
pub const BIN_OP_PENALTY_CODE: i32 = 9;
/// §236
pub const REL_PENALTY_CODE: i32 = 10;
/// §236
pub const PRE_DISPLAY_PENALTY_CODE: i32 = 11;
/// §236
pub const POST_DISPLAY_PENALTY_CODE: i32 = 12;
/// §236
pub const INTER_LINE_PENALTY_CODE: i32 = 13;
/// §236
pub const DOUBLE_HYPHEN_DEMERITS_CODE: i32 = 14;
/// §236
pub const FINAL_HYPHEN_DEMERITS_CODE: i32 = 15;
/// §236
pub const ADJ_DEMERITS_CODE: i32 = 16;
/// §236
pub const MAG_CODE: i32 = 17;
/// §236
pub const DELIMITER_FACTOR_CODE: i32 = 18;
/// §236
pub const LOOSENESS_CODE: i32 = 19;
/// §236
pub const TIME_CODE: i32 = 20;
/// §236
pub const DAY_CODE: i32 = 21;
/// §236
pub const MONTH_CODE: i32 = 22;
/// §236
pub const YEAR_CODE: i32 = 23;
/// §236
pub const SHOW_BOX_BREADTH_CODE: i32 = 24;
/// §236
pub const SHOW_BOX_DEPTH_CODE: i32 = 25;
/// §236
pub const HBADNESS_CODE: i32 = 26;
/// §236
pub const VBADNESS_CODE: i32 = 27;
/// §236
pub const PAUSING_CODE: i32 = 28;
/// §236
pub const TRACING_ONLINE_CODE: i32 = 29;
/// §236
pub const TRACING_MACROS_CODE: i32 = 30;
/// §236
pub const TRACING_STATS_CODE: i32 = 31;
/// §236
pub const TRACING_PARAGRAPHS_CODE: i32 = 32;
/// §236
pub const TRACING_PAGES_CODE: i32 = 33;
/// §236
pub const TRACING_OUTPUT_CODE: i32 = 34;
/// §236
pub const TRACING_LOST_CHARS_CODE: i32 = 35;
/// §236
pub const TRACING_COMMANDS_CODE: i32 = 36;
/// §236
pub const TRACING_RESTORES_CODE: i32 = 37;
/// §236
pub const UC_HYPH_CODE: i32 = 38;
/// §236
pub const OUTPUT_PENALTY_CODE: i32 = 39;
/// §236
pub const MAX_DEAD_CYCLES_CODE: i32 = 40;
/// §236
pub const HANG_AFTER_CODE: i32 = 41;
/// §236
pub const FLOATING_PENALTY_CODE: i32 = 42;
/// §236
pub const GLOBAL_DEFS_CODE: i32 = 43;
/// §236
pub const CUR_FAM_CODE: i32 = 44;
/// §236
pub const ESCAPE_CHAR_CODE: i32 = 45;
/// §236
pub const DEFAULT_HYPHEN_CHAR_CODE: i32 = 46;
/// §236
pub const DEFAULT_SKEW_CHAR_CODE: i32 = 47;
/// §236
pub const END_LINE_CHAR_CODE: i32 = 48;
/// §236
pub const NEW_LINE_CHAR_CODE: i32 = 49;
/// §236
pub const LANGUAGE_CODE: i32 = 50;
/// §236
pub const LEFT_HYPHEN_MIN_CODE: i32 = 51;
/// §236
pub const RIGHT_HYPHEN_MIN_CODE: i32 = 52;
/// §236
pub const HOLDING_INSERTS_CODE: i32 = 53;
/// §236
pub const ERROR_CONTEXT_LINES_CODE: i32 = 54;
/// §236
pub const TEX_INT_PARS: i32 = 55;
/// §236
pub const WEB2C_INT_BASE: i32 = TEX_INT_PARS;
/// §236
pub const CHAR_SUB_DEF_MIN_CODE: i32 = WEB2C_INT_BASE;
/// §236
pub const CHAR_SUB_DEF_MAX_CODE: i32 = WEB2C_INT_BASE + 1;
/// §236
pub const TRACING_CHAR_SUB_DEF_CODE: i32 = WEB2C_INT_BASE + 2;
/// pdfTeX §254
pub const TRACING_STACK_LEVELS_CODE: i32 = WEB2C_INT_BASE + 3;
/// pdfTeX §254
pub const PARTOKEN_CONTEXT_CODE: i32 = WEB2C_INT_BASE + 4;
/// pdfTeX §254
pub const SHOW_STREAM_CODE: i32 = WEB2C_INT_BASE + 5;
/// §236
pub const MUBYTE_IN_CODE: i32 = WEB2C_INT_BASE + 6;
/// §236
pub const MUBYTE_OUT_CODE: i32 = WEB2C_INT_BASE + 7;
/// §236
pub const MUBYTE_LOG_CODE: i32 = WEB2C_INT_BASE + 8;
/// §236
pub const SPEC_OUT_CODE: i32 = WEB2C_INT_BASE + 9;
/// §236
pub const WEB2C_INT_PARS: i32 = WEB2C_INT_BASE + 10;
/// pdfTeX §254
pub const PDFTEX_FIRST_INTEGER_CODE: i32 = WEB2C_INT_PARS;
/// pdfTeX §254
pub const PDF_OUTPUT_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 0;
/// pdfTeX §254
pub const PDF_COMPRESS_LEVEL_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 1;
/// pdfTeX §254
pub const PDF_DECIMAL_DIGITS_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 2;
/// pdfTeX §254
pub const PDF_MOVE_CHARS_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 3;
/// pdfTeX §254
pub const PDF_IMAGE_RESOLUTION_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 4;
/// pdfTeX §254
pub const PDF_PK_RESOLUTION_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 5;
/// pdfTeX §254
pub const PDF_UNIQUE_RESNAME_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 6;
/// pdfTeX §254
pub const PDF_OPTION_ALWAYS_USE_PDFPAGEBOX_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 7;
/// pdfTeX §254
pub const PDF_OPTION_PDF_INCLUSION_ERRORLEVEL_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 8;
/// pdfTeX §254
pub const PDF_MAJOR_VERSION_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 9;
/// pdfTeX §254
pub const PDF_MINOR_VERSION_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 10;
/// pdfTeX §254
pub const PDF_FORCE_PAGEBOX_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 11;
/// pdfTeX §254
pub const PDF_PAGEBOX_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 12;
/// pdfTeX §254
pub const PDF_INCLUSION_ERRORLEVEL_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 13;
/// pdfTeX §254
pub const PDF_GAMMA_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 14;
/// pdfTeX §254
pub const PDF_IMAGE_GAMMA_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 15;
/// pdfTeX §254
pub const PDF_IMAGE_HICOLOR_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 16;
/// pdfTeX §254
pub const PDF_IMAGE_APPLY_GAMMA_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 17;
/// pdfTeX §254
pub const PDF_ADJUST_SPACING_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 18;
/// pdfTeX §254
pub const PDF_PROTRUDE_CHARS_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 19;
/// pdfTeX §254
pub const PDF_TRACING_FONTS_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 20;
/// pdfTeX §254
pub const PDF_OBJCOMPRESSLEVEL_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 21;
/// pdfTeX §254
pub const PDF_ADJUST_INTERWORD_GLUE_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 22;
/// pdfTeX §254
pub const PDF_PREPEND_KERN_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 23;
/// pdfTeX §254
pub const PDF_APPEND_KERN_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 24;
/// pdfTeX §254
pub const PDF_GEN_TOUNICODE_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 25;
/// pdfTeX §254
pub const PDF_DRAFTMODE_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 26;
/// pdfTeX §254
pub const PDF_INCLUSION_COPY_FONT_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 27;
/// pdfTeX §254
pub const PDF_SUPPRESS_WARNING_DUP_DEST_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 28;
/// pdfTeX §254
pub const PDF_SUPPRESS_WARNING_DUP_MAP_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 29;
/// pdfTeX §254
pub const PDF_SUPPRESS_WARNING_PAGE_GROUP_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 30;
/// pdfTeX §254
pub const PDF_INFO_OMIT_DATE_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 31;
/// pdfTeX §254
pub const PDF_SUPPRESS_PTEX_INFO_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 32;
/// pdfTeX §254
pub const PDF_OMIT_CHARSET_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 33;
/// pdfTeX §254
pub const PDF_OMIT_INFO_DICT_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 34;
/// pdfTeX §254
pub const PDF_OMIT_PROCSET_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 35;
/// pdfTeX §254
pub const PDF_PTEX_USE_UNDERSCORE_CODE: i32 = PDFTEX_FIRST_INTEGER_CODE + 36;
/// pdfTeX §254
pub const PDF_INT_PARS: i32 = PDFTEX_FIRST_INTEGER_CODE + 37;
/// pdfTeX §254
pub const ETEX_INT_BASE: i32 = PDF_INT_PARS;
/// pdfTeX §254
pub const TRACING_ASSIGNS_CODE: i32 = ETEX_INT_BASE;
/// pdfTeX §254
pub const TRACING_GROUPS_CODE: i32 = ETEX_INT_BASE + 1;
/// pdfTeX §254
pub const TRACING_IFS_CODE: i32 = ETEX_INT_BASE + 2;
/// pdfTeX §254
pub const TRACING_SCAN_TOKENS_CODE: i32 = ETEX_INT_BASE + 3;
/// pdfTeX §254
pub const TRACING_NESTING_CODE: i32 = ETEX_INT_BASE + 4;
/// pdfTeX §254
pub const PRE_DISPLAY_DIRECTION_CODE: i32 = ETEX_INT_BASE + 5;
/// pdfTeX §254
pub const LAST_LINE_FIT_CODE: i32 = ETEX_INT_BASE + 6;
/// pdfTeX §254
pub const SAVING_VDISCARDS_CODE: i32 = ETEX_INT_BASE + 7;
/// pdfTeX §254
pub const SAVING_HYPH_CODES_CODE: i32 = ETEX_INT_BASE + 8;
/// pdfTeX §254
pub const IGNORE_PRIMITIVE_ERROR_CODE: i32 = ETEX_INT_BASE + 9;
/// `XeTeX` §262
pub const ETEX_STATE_CODE: i32 = ETEX_INT_BASE + 14;
/// pdfTeX §254
pub const ETEX_INT_PARS: i32 = ETEX_STATE_CODE + ETEX_STATES;
/// pdfTeX §254
pub const SYNCTEX_CODE: i32 = ETEX_INT_PARS;
/// §236
pub const INT_PARS: i32 = SYNCTEX_CODE + 1;
/// §236
pub const COUNT_BASE: i32 = INT_BASE + INT_PARS;
/// §236
pub const DEL_CODE_BASE: i32 = COUNT_BASE + 256;
/// §236
pub const DIMEN_BASE: i32 = DEL_CODE_BASE + 256;
/// §247
pub const PAR_INDENT_CODE: i32 = 0;
/// §247
pub const MATH_SURROUND_CODE: i32 = 1;
/// §247
pub const LINE_SKIP_LIMIT_CODE: i32 = 2;
/// §247
pub const HSIZE_CODE: i32 = 3;
/// §247
pub const VSIZE_CODE: i32 = 4;
/// §247
pub const MAX_DEPTH_CODE: i32 = 5;
/// §247
pub const SPLIT_MAX_DEPTH_CODE: i32 = 6;
/// §247
pub const BOX_MAX_DEPTH_CODE: i32 = 7;
/// §247
pub const HFUZZ_CODE: i32 = 8;
/// §247
pub const VFUZZ_CODE: i32 = 9;
/// §247
pub const DELIMITER_SHORTFALL_CODE: i32 = 10;
/// §247
pub const NULL_DELIMITER_SPACE_CODE: i32 = 11;
/// §247
pub const SCRIPT_SPACE_CODE: i32 = 12;
/// §247
pub const PRE_DISPLAY_SIZE_CODE: i32 = 13;
/// §247
pub const DISPLAY_WIDTH_CODE: i32 = 14;
/// §247
pub const DISPLAY_INDENT_CODE: i32 = 15;
/// §247
pub const OVERFULL_RULE_CODE: i32 = 16;
/// §247
pub const HANG_INDENT_CODE: i32 = 17;
/// §247
pub const H_OFFSET_CODE: i32 = 18;
/// §247
pub const V_OFFSET_CODE: i32 = 19;
/// §247
pub const EMERGENCY_STRETCH_CODE: i32 = 20;
/// pdfTeX §265
pub const PDFTEX_FIRST_DIMEN_CODE: i32 = 21;
/// pdfTeX §265
pub const PDF_H_ORIGIN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 0;
/// pdfTeX §265
pub const PDF_V_ORIGIN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 1;
/// pdfTeX §265
pub const PDF_PAGE_WIDTH_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 2;
/// pdfTeX §265
pub const PDF_PAGE_HEIGHT_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 3;
/// pdfTeX §265
pub const PDF_LINK_MARGIN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 4;
/// pdfTeX §265
pub const PDF_DEST_MARGIN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 5;
/// pdfTeX §265
pub const PDF_THREAD_MARGIN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 6;
/// pdfTeX §265
pub const PDF_FIRST_LINE_HEIGHT_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 7;
/// pdfTeX §265
pub const PDF_LAST_LINE_DEPTH_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 8;
/// pdfTeX §265
pub const PDF_EACH_LINE_HEIGHT_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 9;
/// pdfTeX §265
pub const PDF_EACH_LINE_DEPTH_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 10;
/// pdfTeX §265
pub const PDF_IGNORED_DIMEN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 11;
/// pdfTeX §265
pub const PDF_PX_DIMEN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 12;
/// pdfTeX §265
pub const PDFTEX_LAST_DIMEN_CODE: i32 = PDFTEX_FIRST_DIMEN_CODE + 12;
/// §247
pub const DIMEN_PARS: i32 = PDFTEX_LAST_DIMEN_CODE + 1;
/// §247
pub const SCALED_BASE: i32 = DIMEN_BASE + DIMEN_PARS;
/// §247
pub const EQTB_SIZE: i32 = SCALED_BASE + 255;
/// pdfTeX §275
pub const PRIM_PRIME: i32 = 1777;
/// pdfTeX §275
pub const PRIM_BASE: i32 = 1;
/// pdfTeX §275
pub const UNDEFINED_PRIMITIVE: i32 = 0;
/// pdfTeX §275
pub const BIGGEST_CHAR: i32 = 255;
/// §268
pub const RESTORE_OLD_VALUE: i32 = 0;
/// §268
pub const RESTORE_ZERO: i32 = 1;
/// §268
pub const INSERT_TOKEN: i32 = 2;
/// §268
pub const LEVEL_BOUNDARY: i32 = 3;
/// pdfTeX §290
pub const RESTORE_SA: i32 = 4;
/// §269
pub const BOTTOM_LEVEL: i32 = 0;
/// §269
pub const SIMPLE_GROUP: i32 = 1;
/// §269
pub const HBOX_GROUP: i32 = 2;
/// §269
pub const ADJUSTED_HBOX_GROUP: i32 = 3;
/// §269
pub const VBOX_GROUP: i32 = 4;
/// §269
pub const VTOP_GROUP: i32 = 5;
/// §269
pub const ALIGN_GROUP: i32 = 6;
/// §269
pub const NO_ALIGN_GROUP: i32 = 7;
/// §269
pub const OUTPUT_GROUP: i32 = 8;
/// §269
pub const MATH_GROUP: i32 = 9;
/// §269
pub const DISC_GROUP: i32 = 10;
/// §269
pub const INSERT_GROUP: i32 = 11;
/// §269
pub const VCENTER_GROUP: i32 = 12;
/// §269
pub const MATH_CHOICE_GROUP: i32 = 13;
/// §269
pub const SEMI_SIMPLE_GROUP: i32 = 14;
/// §269
pub const MATH_SHIFT_GROUP: i32 = 15;
/// §269
pub const MATH_LEFT_GROUP: i32 = 16;
/// §269
pub const MAX_GROUP_CODE: i32 = 16;
/// `XeTeX` §319
pub const CS_TOKEN_FLAG: i32 = 0x1ffffff;
/// `XeTeX` §319
pub const LEFT_BRACE_TOKEN: i32 = 0x200000;
/// `XeTeX` §319
pub const LEFT_BRACE_LIMIT: i32 = 0x400000;
/// `XeTeX` §319
pub const RIGHT_BRACE_TOKEN: i32 = 0x400000;
/// `XeTeX` §319
pub const RIGHT_BRACE_LIMIT: i32 = 0x600000;
/// `XeTeX` §319
pub const MATH_SHIFT_TOKEN: i32 = 0x600000;
/// `XeTeX` §319
pub const TAB_TOKEN: i32 = 0x800000;
/// `XeTeX` §319
pub const OUT_PARAM_TOKEN: i32 = 0xa00000;
/// `XeTeX` §319
pub const SPACE_TOKEN: i32 = 0x1400020;
/// `XeTeX` §319
pub const LETTER_TOKEN: i32 = 0x1600000;
/// `XeTeX` §319
pub const OTHER_TOKEN: i32 = 0x1800000;
/// `XeTeX` §319
pub const MATCH_TOKEN: i32 = 0x1a00000;
/// `XeTeX` §319
pub const END_MATCH_TOKEN: i32 = 0x1c00000;
/// `XeTeX` §319
pub const PROTECTED_TOKEN: i32 = END_MATCH_TOKEN + 1;
/// §303
pub const MID_LINE: i32 = 1;
/// §303
pub const SKIP_BLANKS: i32 = 2 + MAX_CHAR_CODE;
/// §303
pub const NEW_LINE: i32 = 3 + MAX_CHAR_CODE + MAX_CHAR_CODE;
/// §305
pub const SKIPPING: i32 = 1;
/// §305
pub const DEFINING: i32 = 2;
/// §305
pub const MATCHING: i32 = 3;
/// §305
pub const ALIGNING: i32 = 4;
/// §305
pub const ABSORBING: i32 = 5;
/// §307
pub const TOKEN_LIST: i32 = 0;
/// §307
pub const PARAMETER: i32 = 0;
/// §307
pub const U_TEMPLATE: i32 = 1;
/// §307
pub const V_TEMPLATE: i32 = 2;
/// §307
pub const BACKED_UP: i32 = 3;
/// `XeTeX` §337
pub const INSERTED: i32 = 5;
/// `XeTeX` §337
pub const MACRO: i32 = 6;
/// `XeTeX` §337
pub const OUTPUT_TEXT: i32 = 7;
/// `XeTeX` §337
pub const EVERY_PAR_TEXT: i32 = 8;
/// `XeTeX` §337
pub const EVERY_MATH_TEXT: i32 = 9;
/// `XeTeX` §337
pub const EVERY_DISPLAY_TEXT: i32 = 10;
/// `XeTeX` §337
pub const EVERY_HBOX_TEXT: i32 = 11;
/// `XeTeX` §337
pub const EVERY_VBOX_TEXT: i32 = 12;
/// `XeTeX` §337
pub const EVERY_JOB_TEXT: i32 = 13;
/// `XeTeX` §337
pub const EVERY_CR_TEXT: i32 = 14;
/// `XeTeX` §337
pub const MARK_TEXT: i32 = 15;
/// pdfTeX §329
pub const ETEX_TEXT_OFFSET: i32 = OUTPUT_ROUTINE_LOC - OUTPUT_TEXT;
/// pdfTeX §329
pub const EVERY_EOF_TEXT: i32 = EVERY_EOF_LOC - ETEX_TEXT_OFFSET;
/// §307
pub const WRITE_TEXT: i32 = TOKS_BASE - ETEX_TEXT_OFFSET;
/// §341
pub const SWITCH: i32 = 25;
/// §341
pub const START_CS: i32 = 26;
/// `XeTeX` §388
pub const NO_EXPAND_FLAG: i32 = SPECIAL_CHAR;
/// pdfTeX §408
pub const MARKS_CODE: i32 = 5;
/// §382
pub const TOP_MARK_CODE: i32 = 0;
/// §382
pub const FIRST_MARK_CODE: i32 = 1;
/// §382
pub const BOT_MARK_CODE: i32 = 2;
/// §382
pub const SPLIT_FIRST_MARK_CODE: i32 = 3;
/// §382
pub const SPLIT_BOT_MARK_CODE: i32 = 4;
/// §410
pub const INT_VAL: i32 = 0;
/// §410
pub const DIMEN_VAL: i32 = 1;
/// §410
pub const GLUE_VAL: i32 = 2;
/// §410
pub const MU_VAL: i32 = 3;
/// §410
pub const IDENT_VAL: i32 = 4;
/// §410
pub const TOK_VAL: i32 = 5;
/// pdfTeX §442
pub const LAST_NODE_TYPE_CODE: i32 = GLUE_VAL + 1;
/// §416
pub const INPUT_LINE_NO_CODE: i32 = GLUE_VAL + 2;
/// §416
pub const BADNESS_CODE: i32 = INPUT_LINE_NO_CODE + 1;
/// pdfTeX §442
pub const PDFTEX_FIRST_RINT_CODE: i32 = BADNESS_CODE + 1;
/// pdfTeX §442
pub const PDFTEX_VERSION_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 0;
/// pdfTeX §442
pub const PDF_LAST_OBJ_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 1;
/// pdfTeX §442
pub const PDF_LAST_XFORM_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 2;
/// pdfTeX §442
pub const PDF_LAST_XIMAGE_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 3;
/// pdfTeX §442
pub const PDF_LAST_XIMAGE_PAGES_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 4;
/// pdfTeX §442
pub const PDF_LAST_ANNOT_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 5;
/// pdfTeX §442
pub const PDF_LAST_X_POS_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 6;
/// pdfTeX §442
pub const PDF_LAST_Y_POS_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 7;
/// pdfTeX §442
pub const PDF_RETVAL_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 8;
/// pdfTeX §442
pub const PDF_LAST_XIMAGE_COLORDEPTH_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 9;
/// pdfTeX §442
pub const ELAPSED_TIME_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 10;
/// pdfTeX §442
pub const PDF_SHELL_ESCAPE_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 11;
/// pdfTeX §442
pub const RANDOM_SEED_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 12;
/// pdfTeX §442
pub const PDF_LAST_LINK_CODE: i32 = PDFTEX_FIRST_RINT_CODE + 13;
/// pdfTeX §442
pub const PDFTEX_LAST_ITEM_CODES: i32 = PDFTEX_FIRST_RINT_CODE + 13;
/// pdfTeX §442
pub const ETEX_INT: i32 = PDFTEX_LAST_ITEM_CODES + 1;
/// pdfTeX §442
pub const ETEX_DIM: i32 = ETEX_INT + 8;
/// pdfTeX §442
pub const ETEX_GLUE: i32 = ETEX_DIM + 9;
/// pdfTeX §442
pub const ETEX_MU: i32 = ETEX_GLUE + 1;
/// pdfTeX §442
pub const ETEX_EXPR: i32 = ETEX_MU + 1;
/// §421
pub const MAX_DIMEN: i32 = 0o7777777777;
/// §438
pub const OCTAL_TOKEN: i32 = OTHER_TOKEN + 39;
/// §438
pub const HEX_TOKEN: i32 = OTHER_TOKEN + 34;
/// §445
pub const INFINITY: i32 = 0o17777777777;
/// §445
pub const ZERO_TOKEN: i32 = OTHER_TOKEN + 48;
/// §445
pub const A_TOKEN: i32 = LETTER_TOKEN + 65;
/// §445
pub const OTHER_A_TOKEN: i32 = OTHER_TOKEN + 65;
/// §448
pub const ATTACH_FRACTION: i32 = 88;
/// §448
pub const ATTACH_SIGN: i32 = 89;
/// §463
pub const DEFAULT_RULE: i32 = 26214;
/// §468
pub const NUMBER_CODE: i32 = 0;
/// §468
pub const ROMAN_NUMERAL_CODE: i32 = 1;
/// §468
pub const STRING_CODE: i32 = 2;
/// §468
pub const MEANING_CODE: i32 = 3;
/// §468
pub const FONT_NAME_CODE: i32 = 4;
/// pdfTeX §494
pub const ETEX_CONVERT_BASE: i32 = 5;
/// pdfTeX §494
pub const ETEX_REVISION_CODE: i32 = ETEX_CONVERT_BASE;
/// pdfTeX §494
pub const ETEX_CONVERT_CODES: i32 = ETEX_CONVERT_BASE + 1;
/// pdfTeX §494
pub const EXPANDED_CODE: i32 = ETEX_CONVERT_CODES;
/// pdfTeX §494
pub const PDFTEX_FIRST_EXPAND_CODE: i32 = EXPANDED_CODE + 1;
/// pdfTeX §494
pub const PDFTEX_REVISION_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 0;
/// pdfTeX §494
pub const PDFTEX_BANNER_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 1;
/// pdfTeX §494
pub const PDF_FONT_NAME_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 2;
/// pdfTeX §494
pub const PDF_FONT_OBJNUM_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 3;
/// pdfTeX §494
pub const PDF_FONT_SIZE_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 4;
/// pdfTeX §494
pub const PDF_PAGE_REF_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 5;
/// pdfTeX §494
pub const PDF_XFORM_NAME_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 6;
/// pdfTeX §494
pub const PDF_ESCAPE_STRING_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 7;
/// pdfTeX §494
pub const PDF_ESCAPE_NAME_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 8;
/// pdfTeX §494
pub const LEFT_MARGIN_KERN_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 9;
/// pdfTeX §494
pub const RIGHT_MARGIN_KERN_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 10;
/// pdfTeX §494
pub const PDF_STRCMP_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 11;
/// pdfTeX §494
pub const PDF_COLORSTACK_INIT_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 12;
/// pdfTeX §494
pub const PDF_ESCAPE_HEX_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 13;
/// pdfTeX §494
pub const PDF_UNESCAPE_HEX_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 14;
/// pdfTeX §494
pub const PDF_CREATION_DATE_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 15;
/// pdfTeX §494
pub const PDF_FILE_MOD_DATE_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 16;
/// pdfTeX §494
pub const PDF_FILE_SIZE_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 17;
/// pdfTeX §494
pub const PDF_MDFIVE_SUM_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 18;
/// pdfTeX §494
pub const PDF_FILE_DUMP_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 19;
/// pdfTeX §494
pub const PDF_MATCH_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 20;
/// pdfTeX §494
pub const PDF_LAST_MATCH_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 21;
/// pdfTeX §494
pub const UNIFORM_DEVIATE_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 22;
/// pdfTeX §494
pub const NORMAL_DEVIATE_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 23;
/// pdfTeX §494
pub const PDF_INSERT_HT_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 24;
/// pdfTeX §494
pub const PDF_XIMAGE_BBOX_CODE: i32 = PDFTEX_FIRST_EXPAND_CODE + 25;
/// pdfTeX §494
pub const PDFTEX_CONVERT_CODES: i32 = PDFTEX_FIRST_EXPAND_CODE + 26;
/// §468
pub const JOB_NAME_CODE: i32 = PDFTEX_CONVERT_CODES;
/// §480
pub const CLOSED: i32 = 2;
/// §480
pub const JUST_OPEN: i32 = 1;
/// pdfTeX §513
pub const UNLESS_CODE: i32 = 32;
/// §487
pub const IF_CHAR_CODE: i32 = 0;
/// §487
pub const IF_CAT_CODE: i32 = 1;
/// §487
pub const IF_INT_CODE: i32 = 2;
/// §487
pub const IF_DIM_CODE: i32 = 3;
/// §487
pub const IF_ODD_CODE: i32 = 4;
/// §487
pub const IF_VMODE_CODE: i32 = 5;
/// §487
pub const IF_HMODE_CODE: i32 = 6;
/// §487
pub const IF_MMODE_CODE: i32 = 7;
/// §487
pub const IF_INNER_CODE: i32 = 8;
/// §487
pub const IF_VOID_CODE: i32 = 9;
/// §487
pub const IF_HBOX_CODE: i32 = 10;
/// §487
pub const IF_VBOX_CODE: i32 = 11;
/// §487
pub const IFX_CODE: i32 = 12;
/// §487
pub const IF_EOF_CODE: i32 = 13;
/// §487
pub const IF_TRUE_CODE: i32 = 14;
/// §487
pub const IF_FALSE_CODE: i32 = 15;
/// §487
pub const IF_CASE_CODE: i32 = 16;
/// pdfTeX §513
pub const IF_PDFPRIMITIVE_CODE: i32 = 21;
/// §489
pub const IF_NODE_SIZE: i32 = 2;
/// §489
pub const IF_CODE: i32 = 1;
/// §489
pub const FI_CODE: i32 = 2;
/// §489
pub const ELSE_CODE: i32 = 3;
/// §489
pub const OR_CODE: i32 = 4;
/// §520
pub const FORMAT_AREA_LENGTH: i32 = 0;
/// §520
pub const FORMAT_EXT_LENGTH: i32 = 4;
/// §544
pub const NO_TAG: i32 = 0;
/// §544
pub const LIG_TAG: i32 = 1;
/// §544
pub const LIST_TAG: i32 = 2;
/// §544
pub const EXT_TAG: i32 = 3;
/// §547
pub const SLANT_CODE: i32 = 1;
/// §547
pub const SPACE_CODE: i32 = 2;
/// §547
pub const SPACE_STRETCH_CODE: i32 = 3;
/// §547
pub const SPACE_SHRINK_CODE: i32 = 4;
/// §547
pub const X_HEIGHT_CODE: i32 = 5;
/// §547
pub const QUAD_CODE: i32 = 6;
/// §547
pub const EXTRA_SPACE_CODE: i32 = 7;
/// §549
pub const NON_ADDRESS: i32 = 0;
/// §557
pub const KERN_BASE_OFFSET: i32 = 256 * (128 + MIN_QUARTERWORD);
/// §560
pub const BAD_TFM: i32 = 11;
/// §586
pub const SET_CHAR_0: i32 = 0;
/// §586
pub const SET1: i32 = 128;
/// §586
pub const SET_RULE: i32 = 132;
/// §586
pub const PUT_RULE: i32 = 137;
/// §586
pub const NOP: i32 = 138;
/// §586
pub const BOP: i32 = 139;
/// §586
pub const EOP: i32 = 140;
/// §586
pub const PUSH: i32 = 141;
/// §586
pub const POP: i32 = 142;
/// §586
pub const RIGHT1: i32 = 143;
/// §586
pub const W0: i32 = 147;
/// §586
pub const W1: i32 = 148;
/// §586
pub const X0: i32 = 152;
/// §586
pub const X1: i32 = 153;
/// §586
pub const DOWN1: i32 = 157;
/// §586
pub const Y0: i32 = 161;
/// §586
pub const Y1: i32 = 162;
/// §586
pub const Z0: i32 = 166;
/// §586
pub const Z1: i32 = 167;
/// §586
pub const FNT_NUM_0: i32 = 171;
/// §586
pub const FNT1: i32 = 235;
/// §586
pub const XXX1: i32 = 239;
/// §586
pub const XXX4: i32 = 242;
/// §586
pub const FNT_DEF1: i32 = 243;
/// §586
pub const PRE: i32 = 247;
/// §586
pub const POST: i32 = 248;
/// §586
pub const POST_POST: i32 = 249;
/// §587
pub const ID_BYTE: i32 = 2;
/// §605
pub const MOVEMENT_NODE_SIZE: i32 = 3;
/// §608
pub const Y_HERE: i32 = 1;
/// §608
pub const Z_HERE: i32 = 2;
/// §608
pub const YZ_OK: i32 = 3;
/// §608
pub const Y_OK: i32 = 4;
/// §608
pub const Z_OK: i32 = 5;
/// §608
pub const D_FIXED: i32 = 6;
/// §611
pub const NONE_SEEN: i32 = 0;
/// §611
pub const Y_SEEN: i32 = 6;
/// §611
pub const Z_SEEN: i32 = 12;
/// pdfTeX §643
pub const REVERSED: i32 = 1;
/// pdfTeX §643
pub const DLIST: i32 = 2;
/// pdfTeX §643
pub const LEFT_TO_RIGHT: i32 = 0;
/// pdfTeX §643
pub const RIGHT_TO_LEFT: i32 = 1;
/// §619
pub const MOVE_PAST: i32 = 13;
/// §619
pub const FIN_RULE: i32 = 14;
/// §619
pub const NEXT_P: i32 = 15;
/// pdfTeX §680
pub const NO_ZIP: i32 = 0;
/// pdfTeX §680
pub const ZIP_WRITING: i32 = 1;
/// pdfTeX §680
pub const ZIP_FINISH: i32 = 2;
/// pdfTeX §686
pub const PDF_NEW_LINE_CHAR: i32 = 10;
/// pdfTeX §687
pub const MAX_INTEGER: i32 = 0x7fffffff;
/// pdfTeX §695
pub const OBJ_TYPE_OTHERS: i32 = 0;
/// pdfTeX §695
pub const OBJ_TYPE_PAGE: i32 = 1;
/// pdfTeX §695
pub const OBJ_TYPE_PAGES: i32 = 2;
/// pdfTeX §695
pub const OBJ_TYPE_FONT: i32 = 3;
/// pdfTeX §695
pub const OBJ_TYPE_OUTLINE: i32 = 4;
/// pdfTeX §695
pub const OBJ_TYPE_DEST: i32 = 5;
/// pdfTeX §695
pub const OBJ_TYPE_STRUCT_DEST: i32 = 6;
/// pdfTeX §695
pub const OBJ_TYPE_OBJ: i32 = 7;
/// pdfTeX §695
pub const OBJ_TYPE_XFORM: i32 = 8;
/// pdfTeX §695
pub const OBJ_TYPE_XIMAGE: i32 = 9;
/// pdfTeX §695
pub const OBJ_TYPE_THREAD: i32 = 10;
/// pdfTeX §695
pub const HEAD_TAB_MAX: i32 = OBJ_TYPE_THREAD;
/// pdfTeX §695
pub const PAGES_TREE_KIDS_MAX: i32 = 6;
/// pdfTeX §695
pub const NAME_TREE_KIDS_MAX: i32 = 6;
/// pdfTeX §695
pub const SET_ORIGIN: i32 = 0;
/// pdfTeX §695
pub const DIRECT_PAGE: i32 = 1;
/// pdfTeX §695
pub const DIRECT_ALWAYS: i32 = 2;
/// pdfTeX §695
pub const SCAN_SPECIAL: i32 = 3;
/// pdfTeX §695
pub const PDF_COLORSTACK_NODE_SIZE: i32 = 3;
/// pdfTeX §695
pub const PDF_COLORSTACK_SETTER_NODE_SIZE: i32 = 3;
/// pdfTeX §695
pub const PDF_COLORSTACK_GETTER_NODE_SIZE: i32 = 2;
/// pdfTeX §695
pub const COLORSTACK_SET: i32 = 0;
/// pdfTeX §695
pub const COLORSTACK_PUSH: i32 = 1;
/// pdfTeX §695
pub const COLORSTACK_DATA: i32 = 1;
/// pdfTeX §695
pub const COLORSTACK_POP: i32 = 2;
/// pdfTeX §695
pub const COLORSTACK_CURRENT: i32 = 3;
/// pdfTeX §695
pub const PDF_SETMATRIX_NODE_SIZE: i32 = 2;
/// pdfTeX §695
pub const PDF_SAVE_NODE_SIZE: i32 = 2;
/// pdfTeX §695
pub const PDF_RESTORE_NODE_SIZE: i32 = 2;
/// pdfTeX §695
pub const PDF_REFOBJ_NODE_SIZE: i32 = 2;
/// pdfTeX §695
pub const PDFMEM_OBJ_SIZE: i32 = 4;
/// pdfTeX §695
pub const PDF_REFXFORM_NODE_SIZE: i32 = 5;
/// pdfTeX §695
pub const PDFMEM_XFORM_SIZE: i32 = 6;
/// pdfTeX §695
pub const PDF_REFXIMAGE_NODE_SIZE: i32 = 5;
/// pdfTeX §695
pub const PDFMEM_XIMAGE_SIZE: i32 = 5;
/// pdfTeX §695
pub const PDF_ANNOT_NODE_SIZE: i32 = 7;
/// pdfTeX §695
pub const PDF_ACTION_PAGE: i32 = 0;
/// pdfTeX §695
pub const PDF_ACTION_GOTO: i32 = 1;
/// pdfTeX §695
pub const PDF_ACTION_THREAD: i32 = 2;
/// pdfTeX §695
pub const PDF_ACTION_USER: i32 = 3;
/// pdfTeX §695
pub const PDF_ACTION_SIZE: i32 = 4;
/// pdfTeX §695
pub const PDFMEM_OUTLINE_SIZE: i32 = 8;
/// pdfTeX §695
pub const PDF_DEST_XYZ: i32 = 0;
/// pdfTeX §695
pub const PDF_DEST_FIT: i32 = 1;
/// pdfTeX §695
pub const PDF_DEST_FITH: i32 = 2;
/// pdfTeX §695
pub const PDF_DEST_FITV: i32 = 3;
/// pdfTeX §695
pub const PDF_DEST_FITB: i32 = 4;
/// pdfTeX §695
pub const PDF_DEST_FITBH: i32 = 5;
/// pdfTeX §695
pub const PDF_DEST_FITBV: i32 = 6;
/// pdfTeX §695
pub const PDF_DEST_FITR: i32 = 7;
/// pdfTeX §695
pub const PDF_DEST_NODE_SIZE: i32 = 7;
/// pdfTeX §695
pub const PDF_THREAD_NODE_SIZE: i32 = 7;
/// pdfTeX §695
pub const PDFMEM_BEAD_SIZE: i32 = 5;
/// pdfTeX §695
pub const SNAP_NODE_SIZE: i32 = 3;
/// pdfTeX §703
pub const NEW_FONT_TYPE: i32 = 0;
/// pdfTeX §703
pub const VIRTUAL_FONT_TYPE: i32 = 1;
/// pdfTeX §703
pub const REAL_FONT_TYPE: i32 = 2;
/// pdfTeX §703
pub const SUBST_FONT_TYPE: i32 = 3;
/// pdfTeX §710
pub const VF_MAX_PACKET_LENGTH: i32 = 10000;
/// pdfTeX §710
pub const DO_CHAR: i32 = 70;
/// pdfTeX §710
pub const LONG_CHAR: i32 = 242;
/// pdfTeX §710
pub const VF_ID: i32 = 202;
/// pdfTeX §710
pub const PUT1: i32 = 133;
/// §644
pub const EXACTLY: i32 = 0;
/// §644
pub const ADDITIONAL: i32 = 1;
/// pdfTeX §823
pub const CAL_EXPAND_RATIO: i32 = 2;
/// pdfTeX §823
pub const SUBST_EX_FONT: i32 = 3;
/// pdfTeX §823
pub const SUBSTITUTED: i32 = 3;
/// §681
pub const NOAD_SIZE: i32 = 4;
/// §681
pub const MATH_CHAR: i32 = 1;
/// §681
pub const SUB_BOX: i32 = 2;
/// §681
pub const SUB_MLIST: i32 = 3;
/// §681
pub const MATH_TEXT_CHAR: i32 = 4;
/// §682
pub const ORD_NOAD: i32 = UNSET_NODE + 3;
/// §682
pub const OP_NOAD: i32 = ORD_NOAD + 1;
/// §682
pub const BIN_NOAD: i32 = ORD_NOAD + 2;
/// §682
pub const REL_NOAD: i32 = ORD_NOAD + 3;
/// §682
pub const OPEN_NOAD: i32 = ORD_NOAD + 4;
/// §682
pub const CLOSE_NOAD: i32 = ORD_NOAD + 5;
/// §682
pub const PUNCT_NOAD: i32 = ORD_NOAD + 6;
/// §682
pub const INNER_NOAD: i32 = ORD_NOAD + 7;
/// §682
pub const LIMITS: i32 = 1;
/// §682
pub const NO_LIMITS: i32 = 2;
/// §683
pub const RADICAL_NOAD: i32 = INNER_NOAD + 1;
/// §683
pub const RADICAL_NOAD_SIZE: i32 = 5;
/// §683
pub const FRACTION_NOAD: i32 = RADICAL_NOAD + 1;
/// §683
pub const FRACTION_NOAD_SIZE: i32 = 6;
/// §683
pub const DEFAULT_CODE: i32 = 0o10000000000;
/// §687
pub const UNDER_NOAD: i32 = FRACTION_NOAD + 1;
/// §687
pub const OVER_NOAD: i32 = UNDER_NOAD + 1;
/// §687
pub const ACCENT_NOAD: i32 = OVER_NOAD + 1;
/// §687
pub const ACCENT_NOAD_SIZE: i32 = 5;
/// §687
pub const VCENTER_NOAD: i32 = ACCENT_NOAD + 1;
/// §687
pub const LEFT_NOAD: i32 = VCENTER_NOAD + 1;
/// §687
pub const RIGHT_NOAD: i32 = LEFT_NOAD + 1;
/// pdfTeX §863
pub const MIDDLE_NOAD: i32 = 1;
/// §688
pub const STYLE_NODE: i32 = UNSET_NODE + 1;
/// §688
pub const STYLE_NODE_SIZE: i32 = 3;
/// §688
pub const DISPLAY_STYLE: i32 = 0;
/// §688
pub const TEXT_STYLE: i32 = 2;
/// §688
pub const SCRIPT_STYLE: i32 = 4;
/// §688
pub const SCRIPT_SCRIPT_STYLE: i32 = 6;
/// §688
pub const CRAMPED: i32 = 1;
/// §689
pub const CHOICE_NODE: i32 = UNSET_NODE + 2;
/// §699
pub const TEXT_SIZE: i32 = 0;
/// `XeTeX` §12
pub const SCRIPT_SIZE: i32 = NUMBER_MATH_FAMILIES;
/// `XeTeX` §12
pub const SCRIPT_SCRIPT_SIZE: i32 = NUMBER_MATH_FAMILIES + NUMBER_MATH_FAMILIES;
/// §700
pub const TOTAL_MATHSY_PARAMS: i32 = 22;
/// §701
pub const TOTAL_MATHEX_PARAMS: i32 = 13;
/// §726
pub const DONE_WITH_NOAD: i32 = 80;
/// §726
pub const DONE_WITH_NODE: i32 = 81;
/// §726
pub const CHECK_DIMENSIONS: i32 = 82;
/// §726
pub const DELETE_Q: i32 = 83;
/// §770
pub const ALIGN_STACK_NODE_SIZE: i32 = 6;
/// `XeTeX` §828
pub const SPAN_CODE: i32 = SPECIAL_CHAR;
/// `XeTeX` §828
pub const CR_CODE: i32 = SPAN_CODE + 1;
/// §780
pub const CR_CR_CODE: i32 = CR_CODE + 1;
/// §780
pub const END_TEMPLATE_TOKEN: i32 = CS_TOKEN_FLAG + FROZEN_END_TEMPLATE;
/// §797
pub const SPAN_NODE_SIZE: i32 = 2;
/// §817
pub const TIGHT_FIT: i32 = 3;
/// §817
pub const LOOSE_FIT: i32 = 1;
/// §817
pub const VERY_LOOSE_FIT: i32 = 0;
/// §817
pub const DECENT_FIT: i32 = 2;
/// pdfTeX §995
pub const ACTIVE_NODE_SIZE_NORMAL: i32 = 3;
/// §819
pub const UNHYPHENATED: i32 = 0;
/// §819
pub const HYPHENATED: i32 = 1;
/// §821
pub const PASSIVE_NODE_SIZE: i32 = 2;
/// §822
pub const DELTA_NODE_SIZE: i32 = 9;
/// §822
pub const DELTA_NODE: i32 = 2;
/// §829
pub const DEACTIVATE: i32 = 60;
/// §833
pub const AWFUL_BAD: i32 = 0o7777777777;
/// pdfTeX §1145
pub const DISCARD_OR_MOVE: i32 = 60;
/// §970
pub const UPDATE_HEIGHTS: i32 = 90;
/// §974
pub const DEPLORABLE: i32 = 100000;
/// §980
pub const INSERTS_ONLY: i32 = 1;
/// §980
pub const BOX_THERE: i32 = 2;
/// §981
pub const PAGE_INS_NODE_SIZE: i32 = 4;
/// §981
pub const INSERTING: i32 = 0;
/// §981
pub const SPLIT_UP: i32 = 1;
/// §994
pub const CONTRIBUTE: i32 = 80;
/// §1030
pub const BIG_SWITCH: i32 = 60;
/// §1030
pub const MAIN_LOOP: i32 = 70;
/// §1030
pub const MAIN_LOOP_WRAPUP: i32 = 80;
/// §1030
pub const MAIN_LOOP_MOVE: i32 = 90;
/// §1030
pub const MAIN_LOOP_MOVE_LIG: i32 = 95;
/// §1030
pub const MAIN_LOOP_LOOKAHEAD: i32 = 100;
/// §1030
pub const MAIN_LIG_LOOP: i32 = 110;
/// §1030
pub const APPEND_NORMAL_SPACE: i32 = 120;
/// §1058
pub const FIL_CODE: i32 = 0;
/// §1058
pub const FILL_CODE: i32 = 1;
/// §1058
pub const SS_CODE: i32 = 2;
/// §1058
pub const FIL_NEG_CODE: i32 = 3;
/// §1058
pub const SKIP_CODE: i32 = 4;
/// §1058
pub const MSKIP_CODE: i32 = 5;
/// §1071
pub const BOX_FLAG: i32 = 0o10000000000;
/// pdfTeX §1249
pub const GLOBAL_BOX_FLAG: i32 = 0o10000100000;
/// §1071
pub const SHIP_OUT_FLAG: i32 = 0o10000200000;
/// §1071
pub const LEADER_FLAG: i32 = 0o10000200001;
/// §1071
pub const BOX_CODE: i32 = 0;
/// §1071
pub const COPY_CODE: i32 = 1;
/// §1071
pub const LAST_BOX_CODE: i32 = 2;
/// §1071
pub const VSPLIT_CODE: i32 = 3;
/// §1071
pub const VTOP_CODE: i32 = 4;
/// §1178
pub const ABOVE_CODE: i32 = 0;
/// §1178
pub const OVER_CODE: i32 = 1;
/// §1178
pub const ATOP_CODE: i32 = 2;
/// §1178
pub const DELIMITED_CODE: i32 = 3;
/// §1222
pub const CHAR_DEF_CODE: i32 = 0;
/// §1222
pub const MATH_CHAR_DEF_CODE: i32 = 1;
/// §1222
pub const COUNT_DEF_CODE: i32 = 2;
/// §1222
pub const DIMEN_DEF_CODE: i32 = 3;
/// §1222
pub const SKIP_DEF_CODE: i32 = 4;
/// §1222
pub const MU_SKIP_DEF_CODE: i32 = 5;
/// §1222
pub const TOKS_DEF_CODE: i32 = 6;
/// §1222
pub const CHAR_SUB_DEF_CODE: i32 = 7;
/// §1291
pub const SHOW_CODE: i32 = 0;
/// §1291
pub const SHOW_BOX_CODE: i32 = 1;
/// §1291
pub const SHOW_THE_CODE: i32 = 2;
/// §1291
pub const SHOW_LISTS_CODE: i32 = 3;
/// §1303
pub const BAD_FMT: i32 = 6666;
/// §1338
pub const BREAKPOINT: i32 = 888;
/// §1341
pub const WRITE_NODE_SIZE: i32 = 2;
/// §1341
pub const OPEN_NODE_SIZE: i32 = 3;
/// §1341
pub const OPEN_NODE: i32 = 0;
/// §1341
pub const WRITE_NODE: i32 = 1;
/// §1341
pub const CLOSE_NODE: i32 = 2;
/// §1341
pub const SPECIAL_NODE: i32 = 3;
/// pdfTeX §1521
pub const LATESPECIAL_NODE: i32 = 4;
/// §1341
pub const LANGUAGE_NODE: i32 = 5;
/// §1341
pub const MUBYTE_ZERO: i32 = 64;
/// §1344
pub const IMMEDIATE_CODE: i32 = 5;
/// §1344
pub const SET_LANGUAGE_CODE: i32 = 6;
/// pdfTeX §1524
pub const PDFTEX_FIRST_EXTENSION_CODE: i32 = 7;
/// pdfTeX §1524
pub const PDF_LITERAL_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 0;
/// pdfTeX §1524
pub const PDF_LATELITERAL_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 1;
/// pdfTeX §1524
pub const PDF_OBJ_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 2;
/// pdfTeX §1524
pub const PDF_REFOBJ_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 3;
/// pdfTeX §1524
pub const PDF_XFORM_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 4;
/// pdfTeX §1524
pub const PDF_REFXFORM_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 5;
/// pdfTeX §1524
pub const PDF_XIMAGE_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 6;
/// pdfTeX §1524
pub const PDF_REFXIMAGE_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 7;
/// pdfTeX §1524
pub const PDF_ANNOT_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 8;
/// pdfTeX §1524
pub const PDF_START_LINK_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 9;
/// pdfTeX §1524
pub const PDF_END_LINK_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 10;
/// pdfTeX §1524
pub const PDF_OUTLINE_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 11;
/// pdfTeX §1524
pub const PDF_DEST_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 12;
/// pdfTeX §1524
pub const PDF_THREAD_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 13;
/// pdfTeX §1524
pub const PDF_START_THREAD_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 14;
/// pdfTeX §1524
pub const PDF_END_THREAD_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 15;
/// pdfTeX §1524
pub const PDF_SAVE_POS_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 16;
/// pdfTeX §1524
pub const PDF_INFO_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 17;
/// pdfTeX §1524
pub const PDF_CATALOG_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 18;
/// pdfTeX §1524
pub const PDF_NAMES_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 19;
/// pdfTeX §1524
pub const PDF_FONT_ATTR_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 20;
/// pdfTeX §1524
pub const PDF_INCLUDE_CHARS_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 21;
/// pdfTeX §1524
pub const PDF_MAP_FILE_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 22;
/// pdfTeX §1524
pub const PDF_MAP_LINE_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 23;
/// pdfTeX §1524
pub const PDF_TRAILER_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 24;
/// pdfTeX §1524
pub const PDF_TRAILER_ID_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 25;
/// pdfTeX §1524
pub const RESET_TIMER_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 26;
/// pdfTeX §1524
pub const PDF_FONT_EXPAND_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 27;
/// pdfTeX §1524
pub const SET_RANDOM_SEED_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 28;
/// pdfTeX §1524
pub const PDF_SNAP_REF_POINT_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 29;
/// pdfTeX §1524
pub const PDF_SNAPY_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 30;
/// pdfTeX §1524
pub const PDF_SNAPY_COMP_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 31;
/// pdfTeX §1524
pub const PDF_GLYPH_TO_UNICODE_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 32;
/// pdfTeX §1524
pub const PDF_COLORSTACK_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 33;
/// pdfTeX §1524
pub const PDF_SETMATRIX_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 34;
/// pdfTeX §1524
pub const PDF_SAVE_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 35;
/// pdfTeX §1524
pub const PDF_RESTORE_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 36;
/// pdfTeX §1524
pub const PDF_NOBUILTIN_TOUNICODE_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 37;
/// pdfTeX §1524
pub const PDF_INTERWORD_SPACE_ON_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 38;
/// pdfTeX §1524
pub const PDF_INTERWORD_SPACE_OFF_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 39;
/// pdfTeX §1524
pub const PDF_FAKE_SPACE_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 40;
/// pdfTeX §1524
pub const PDF_RUNNING_LINK_OFF_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 41;
/// pdfTeX §1524
pub const PDF_RUNNING_LINK_ON_NODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 42;
/// pdfTeX §1524
pub const PDF_SPACE_FONT_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 43;
/// pdfTeX §1524
pub const PDFTEX_LAST_EXTENSION_CODE: i32 = PDFTEX_FIRST_EXTENSION_CODE + 43;
/// §1371
pub const END_WRITE_TOKEN: i32 = CS_TOKEN_FLAG + END_WRITE;
/// pdfTeX §1649
pub const ETEX_STATE_BASE: i32 = INT_BASE + ETEX_STATE_CODE;
/// pdfTeX §1649
pub const ETEX_VERSION_CODE: i32 = ETEX_INT;
/// pdfTeX §1663
pub const CURRENT_GROUP_LEVEL_CODE: i32 = ETEX_INT + 1;
/// pdfTeX §1663
pub const CURRENT_GROUP_TYPE_CODE: i32 = ETEX_INT + 2;
/// pdfTeX §1666
pub const CURRENT_IF_LEVEL_CODE: i32 = ETEX_INT + 3;
/// pdfTeX §1666
pub const CURRENT_IF_TYPE_CODE: i32 = ETEX_INT + 4;
/// pdfTeX §1666
pub const CURRENT_IF_BRANCH_CODE: i32 = ETEX_INT + 5;
/// pdfTeX §1669
pub const FONT_CHAR_WD_CODE: i32 = ETEX_DIM;
/// pdfTeX §1669
pub const FONT_CHAR_HT_CODE: i32 = ETEX_DIM + 1;
/// pdfTeX §1669
pub const FONT_CHAR_DP_CODE: i32 = ETEX_DIM + 2;
/// pdfTeX §1669
pub const FONT_CHAR_IC_CODE: i32 = ETEX_DIM + 3;
/// pdfTeX §1672
pub const PAR_SHAPE_LENGTH_CODE: i32 = ETEX_DIM + 4;
/// pdfTeX §1672
pub const PAR_SHAPE_INDENT_CODE: i32 = ETEX_DIM + 5;
/// pdfTeX §1672
pub const PAR_SHAPE_DIMEN_CODE: i32 = ETEX_DIM + 6;
/// pdfTeX §1675
pub const SHOW_GROUPS: i32 = 4;
/// pdfTeX §1684
pub const SHOW_TOKENS: i32 = 5;
/// pdfTeX §1689
pub const SHOW_IFS: i32 = 6;
/// pdfTeX §1719
pub const EDGE_NODE: i32 = STYLE_NODE;
/// pdfTeX §1719
pub const EDGE_NODE_SIZE: i32 = STYLE_NODE_SIZE;
/// pdfTeX §1762
pub const IF_DEF_CODE: i32 = 17;
/// pdfTeX §1762
pub const IF_CS_CODE: i32 = 18;
/// pdfTeX §1762
pub const IF_FONT_CHAR_CODE: i32 = 19;
/// pdfTeX §1762
pub const IF_IN_CSNAME_CODE: i32 = 20;
/// pdfTeX §1762
pub const IF_PDFABS_NUM_CODE: i32 = 22;
/// pdfTeX §1762
pub const IF_PDFABS_DIM_CODE: i32 = 23;
/// pdfTeX §1783
pub const EXPR_NONE: i32 = 0;
/// pdfTeX §1783
pub const EXPR_ADD: i32 = 1;
/// pdfTeX §1783
pub const EXPR_SUB: i32 = 2;
/// pdfTeX §1783
pub const EXPR_MULT: i32 = 3;
/// pdfTeX §1783
pub const EXPR_DIV: i32 = 4;
/// pdfTeX §1783
pub const EXPR_SCALE: i32 = 5;
/// pdfTeX §1788
pub const EXPR_NODE_SIZE: i32 = 4;
/// pdfTeX §1799
pub const TOO_BIG: i32 = 88;
/// pdfTeX §1801
pub const GLUE_STRETCH_ORDER_CODE: i32 = ETEX_INT + 6;
/// pdfTeX §1801
pub const GLUE_SHRINK_ORDER_CODE: i32 = ETEX_INT + 7;
/// pdfTeX §1801
pub const GLUE_STRETCH_CODE: i32 = ETEX_DIM + 7;
/// pdfTeX §1801
pub const GLUE_SHRINK_CODE: i32 = ETEX_DIM + 8;
/// pdfTeX §1805
pub const MU_TO_GLUE_CODE: i32 = ETEX_GLUE;
/// pdfTeX §1805
pub const GLUE_TO_MU_CODE: i32 = ETEX_MU;
/// pdfTeX §1815
pub const BOX_VAL: i32 = 4;
/// pdfTeX §1815
pub const MARK_VAL: i32 = 6;
/// pdfTeX §1815
pub const DIMEN_VAL_LIMIT: i32 = 0x20;
/// pdfTeX §1815
pub const MU_VAL_LIMIT: i32 = 0x40;
/// pdfTeX §1815
pub const BOX_VAL_LIMIT: i32 = 0x50;
/// pdfTeX §1815
pub const TOK_VAL_LIMIT: i32 = 0x60;
/// pdfTeX §1815
pub const INDEX_NODE_SIZE: i32 = 9;
/// pdfTeX §1820
pub const POINTER_NODE_SIZE: i32 = 2;
/// pdfTeX §1820
pub const WORD_NODE_SIZE: i32 = 3;
/// pdfTeX §1820
pub const MARK_CLASS_NODE_SIZE: i32 = 4;
/// pdfTeX §1825
pub const VSPLIT_INIT: i32 = 0;
/// pdfTeX §1825
pub const FIRE_UP_INIT: i32 = 1;
/// pdfTeX §1825
pub const FIRE_UP_DONE: i32 = 2;
/// pdfTeX §1825
pub const DESTROY_MARKS: i32 = 3;
/// pdfTeX §1842
pub const ACTIVE_NODE_SIZE_EXTENDED: i32 = 5;
/// `XeTeX` §319
pub const MAX_CHAR_VAL: i32 = 0x200000;
/// `XeTeX` §234
pub const XETEX_MATH_GIVEN: i32 = 70;
/// `XeTeX` §235
pub const XETEX_DEF_CODE: i32 = 87;
/// `XeTeX` §250
pub const XETEX_LINEBREAK_SKIP_CODE: i32 = 15;
/// `XeTeX` §256
pub const XETEX_INTER_CHAR_LOC: i32 = EVERY_EOF_LOC + 1;
/// `XeTeX` §12
pub const NUMBER_MATH_FAMILIES: i32 = 256;
/// `XeTeX` §12
pub const NUMBER_MATH_FONTS: i32 =
    NUMBER_MATH_FAMILIES + NUMBER_MATH_FAMILIES + NUMBER_MATH_FAMILIES;
/// `XeTeX` §12
pub const MATH_FONT_BIGGEST: i32 = NUMBER_MATH_FONTS - 1;
/// `XeTeX` §337
pub const BACKED_UP_CHAR: i32 = 4;
/// `XeTeX` §337
pub const INTER_CHAR_TEXT: i32 = XETEX_INTER_CHAR_LOC - ETEX_TEXT_OFFSET;
/// `XeTeX` §12
pub const TOO_BIG_CHAR: i32 = 65536;
/// `XeTeX` §12
pub const BIGGEST_USV: i32 = 0x10ffff;
/// `XeTeX` §12
pub const TOO_BIG_USV: i32 = 0x110000;
/// `XeTeX` §12
pub const NUMBER_USVS: i32 = 0x110000;
/// `XeTeX` §12
pub const SPECIAL_CHAR: i32 = 0x110001;
/// `XeTeX` §2
pub const XETEX_VERSION: i32 = 0;
/// `XeTeX` §2
pub const XETEX_DASH_BREAK_CODE: i32 = 1;
/// `XeTeX` §2
pub const XETEX_UPWARDS_CODE: i32 = 2;
/// `XeTeX` §2
pub const XETEX_USE_GLYPH_METRICS_CODE: i32 = 3;
/// `XeTeX` §2
pub const XETEX_INTER_CHAR_TOKENS_CODE: i32 = 4;
/// `XeTeX` §2
pub const XETEX_INPUT_NORMALIZATION_CODE: i32 = 5;
/// `XeTeX` §2
pub const XETEX_DEFAULT_INPUT_MODE_CODE: i32 = 6;
/// `XeTeX` §2
pub const XETEX_INPUT_MODE_AUTO: i32 = 0;
/// `XeTeX` §2
pub const XETEX_INPUT_MODE_UTF8: i32 = 1;
/// `XeTeX` §2
pub const XETEX_INPUT_MODE_UTF16BE: i32 = 2;
/// `XeTeX` §2
pub const XETEX_INPUT_MODE_UTF16LE: i32 = 3;
/// `XeTeX` §2
pub const XETEX_INPUT_MODE_RAW: i32 = 4;
/// `XeTeX` §2
pub const XETEX_INPUT_MODE_ICU_MAPPING: i32 = 5;
/// `XeTeX` §2
pub const XETEX_DEFAULT_INPUT_ENCODING_CODE: i32 = 7;
/// `XeTeX` §2
pub const XETEX_TRACING_FONTS_CODE: i32 = 8;
/// `XeTeX` §2
pub const XETEX_INTERWORD_SPACE_SHAPING_CODE: i32 = 9;
/// `XeTeX` §2
pub const XETEX_GENERATE_ACTUAL_TEXT_CODE: i32 = 10;
/// `XeTeX` §2
pub const XETEX_HYPHENATABLE_LENGTH_CODE: i32 = 11;
/// `XeTeX` §12
pub const BIGGEST_REG: i32 = 255;
/// `XeTeX` §12
pub const NUMBER_REGS: i32 = 256;
/// `XeTeX` §12
pub const FONT_BIGGEST: i32 = 255;
/// `XeTeX` §12
pub const NUMBER_FONTS: i32 = FONT_BIGGEST - FONT_BASE + 2;
/// `XeTeX` §12
pub const BIGGEST_LANG: i32 = 255;
/// `XeTeX` §12
pub const TOO_BIG_LANG: i32 = 256;
/// `XeTeX` §12
pub const HYPHENATABLE_LENGTH_LIMIT: i32 = 4095;
/// `XeTeX` §80
pub const OUTPUT_FAILURE: i32 = 4;
/// `XeTeX` §169
pub const NATIVE_WORD_NODE: i32 = 40;
/// `XeTeX` §169
pub const NATIVE_WORD_NODE_AT: i32 = 41;
/// `XeTeX` §169
pub const GLYPH_NODE: i32 = 42;
/// `XeTeX` §170
pub const PIC_NODE: i32 = 43;
/// `XeTeX` §170
pub const PDF_NODE: i32 = 44;
/// `XeTeX` §179
pub const SPACE_ADJUSTMENT: i32 = 3;
/// `XeTeX` §258
pub const VAR_FAM_CLASS: i32 = 7;
/// `XeTeX` §258
pub const ACTIVE_MATH_CHAR: i32 = 0x1fffff;
/// `XeTeX` §262
pub const SUPPRESS_FONTNOTFOUND_ERROR_CODE: i32 = ETEX_INT_BASE + 10;
/// `XeTeX` §262
pub const XETEX_LINEBREAK_LOCALE_CODE: i32 = ETEX_INT_BASE + 11;
/// `XeTeX` §262
pub const XETEX_LINEBREAK_PENALTY_CODE: i32 = ETEX_INT_BASE + 12;
/// `XeTeX` §262
pub const XETEX_PROTRUDE_CHARS_CODE: i32 = ETEX_INT_BASE + 13;
/// `XeTeX` §447
pub const CHAR_CLASS_LIMIT: i32 = 0x1000;
/// `XeTeX` §447
pub const CHAR_CLASS_IGNORED: i32 = CHAR_CLASS_LIMIT;
/// `XeTeX` §447
pub const CHAR_CLASS_BOUNDARY: i32 = (CHAR_CLASS_IGNORED - 1);
/// `XeTeX` §450
pub const XETEX_INT: i32 = ETEX_EXPR + 4;
/// `XeTeX` §450
pub const XETEX_VERSION_CODE: i32 = XETEX_INT + 0;
/// `XeTeX` §450
pub const XETEX_COUNT_GLYPHS_CODE: i32 = XETEX_INT + 1;
/// `XeTeX` §450
pub const XETEX_COUNT_VARIATIONS_CODE: i32 = XETEX_INT + 2;
/// `XeTeX` §450
pub const XETEX_VARIATION_CODE: i32 = XETEX_INT + 3;
/// `XeTeX` §450
pub const XETEX_FIND_VARIATION_BY_NAME_CODE: i32 = XETEX_INT + 4;
/// `XeTeX` §450
pub const XETEX_VARIATION_MIN_CODE: i32 = XETEX_INT + 5;
/// `XeTeX` §450
pub const XETEX_VARIATION_MAX_CODE: i32 = XETEX_INT + 6;
/// `XeTeX` §450
pub const XETEX_VARIATION_DEFAULT_CODE: i32 = XETEX_INT + 7;
/// `XeTeX` §450
pub const XETEX_COUNT_FEATURES_CODE: i32 = XETEX_INT + 8;
/// `XeTeX` §450
pub const XETEX_FEATURE_CODE_CODE: i32 = XETEX_INT + 9;
/// `XeTeX` §450
pub const XETEX_FIND_FEATURE_BY_NAME_CODE: i32 = XETEX_INT + 10;
/// `XeTeX` §450
pub const XETEX_IS_EXCLUSIVE_FEATURE_CODE: i32 = XETEX_INT + 11;
/// `XeTeX` §450
pub const XETEX_COUNT_SELECTORS_CODE: i32 = XETEX_INT + 12;
/// `XeTeX` §450
pub const XETEX_SELECTOR_CODE_CODE: i32 = XETEX_INT + 13;
/// `XeTeX` §450
pub const XETEX_FIND_SELECTOR_BY_NAME_CODE: i32 = XETEX_INT + 14;
/// `XeTeX` §450
pub const XETEX_IS_DEFAULT_SELECTOR_CODE: i32 = XETEX_INT + 15;
/// `XeTeX` §450
pub const XETEX_OT_COUNT_SCRIPTS_CODE: i32 = XETEX_INT + 16;
/// `XeTeX` §450
pub const XETEX_OT_COUNT_LANGUAGES_CODE: i32 = XETEX_INT + 17;
/// `XeTeX` §450
pub const XETEX_OT_COUNT_FEATURES_CODE: i32 = XETEX_INT + 18;
/// `XeTeX` §450
pub const XETEX_OT_SCRIPT_CODE: i32 = XETEX_INT + 19;
/// `XeTeX` §450
pub const XETEX_OT_LANGUAGE_CODE: i32 = XETEX_INT + 20;
/// `XeTeX` §450
pub const XETEX_OT_FEATURE_CODE: i32 = XETEX_INT + 21;
/// `XeTeX` §450
pub const XETEX_MAP_CHAR_TO_GLYPH_CODE: i32 = XETEX_INT + 22;
/// `XeTeX` §450
pub const XETEX_GLYPH_INDEX_CODE: i32 = XETEX_INT + 23;
/// `XeTeX` §450
pub const XETEX_FONT_TYPE_CODE: i32 = XETEX_INT + 24;
/// `XeTeX` §450
pub const XETEX_FIRST_CHAR_CODE: i32 = XETEX_INT + 25;
/// `XeTeX` §450
pub const XETEX_LAST_CHAR_CODE: i32 = XETEX_INT + 26;
/// `XeTeX` §450
pub const XETEX_PDF_PAGE_COUNT_CODE: i32 = XETEX_INT + 27;
/// `XeTeX` §450
pub const XETEX_LAST_ITEM_CODES: i32 = XETEX_INT + 27;
/// `XeTeX` §450
pub const XETEX_DIM: i32 = XETEX_LAST_ITEM_CODES + 1;
/// `XeTeX` §450
pub const XETEX_GLYPH_BOUNDS_CODE: i32 = XETEX_DIM + 0;
/// `XeTeX` §450
pub const XETEX_LAST_DIM_CODES: i32 = XETEX_DIM + 0;
/// `XeTeX` §503
pub const XETEX_FIRST_EXPAND_CODE: i32 = JOB_NAME_CODE + 1;
/// `XeTeX` §503
pub const XETEX_REVISION_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 0;
/// `XeTeX` §503
pub const XETEX_VARIATION_NAME_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 1;
/// `XeTeX` §503
pub const XETEX_FEATURE_NAME_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 2;
/// `XeTeX` §503
pub const XETEX_SELECTOR_NAME_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 3;
/// `XeTeX` §503
pub const XETEX_GLYPH_NAME_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 4;
/// `XeTeX` §503
pub const XETEX_UCHAR_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 5;
/// `XeTeX` §503
pub const XETEX_UCHARCAT_CODE: i32 = XETEX_FIRST_EXPAND_CODE + 6;
/// `XeTeX` §503
pub const XETEX_CONVERT_CODES: i32 = XETEX_FIRST_EXPAND_CODE + 7;
/// `XeTeX` §522
pub const IF_PRIMITIVE_CODE: i32 = 21;
/// `XeTeX` §584
pub const OTGR_FONT_FLAG: i32 = 0xfffe;
/// `XeTeX` §584
pub const AAT_FONT_FLAG: i32 = 0xffff;
/// `XeTeX` §622
pub const DEFINE_NATIVE_FONT: i32 = 252;
/// `XeTeX` §622
pub const SET_GLYPHS: i32 = 253;
/// `XeTeX` §622
pub const SET_TEXT_AND_GLYPHS: i32 = 254;
/// `XeTeX` §729
pub const FIXED_ACC: i32 = 1;
/// `XeTeX` §729
pub const BOTTOM_ACC: i32 = 2;
/// `XeTeX` §742
pub const SCRIPTPERCENTSCALEDOWN: i32 = 0;
/// `XeTeX` §742
pub const SCRIPTSCRIPTPERCENTSCALEDOWN: i32 = 1;
/// `XeTeX` §742
pub const DELIMITEDSUBFORMULAMINHEIGHT: i32 = 2;
/// `XeTeX` §742
pub const DISPLAYOPERATORMINHEIGHT: i32 = 3;
/// `XeTeX` §742
pub const MATHLEADING: i32 = 4;
/// `XeTeX` §742
pub const FIRSTMATHVALUERECORD: i32 = MATHLEADING;
/// `XeTeX` §742
pub const AXISHEIGHT: i32 = 5;
/// `XeTeX` §742
pub const ACCENTBASEHEIGHT: i32 = 6;
/// `XeTeX` §742
pub const FLATTENEDACCENTBASEHEIGHT: i32 = 7;
/// `XeTeX` §742
pub const SUBSCRIPTSHIFTDOWN: i32 = 8;
/// `XeTeX` §742
pub const SUBSCRIPTTOPMAX: i32 = 9;
/// `XeTeX` §742
pub const SUBSCRIPTBASELINEDROPMIN: i32 = 10;
/// `XeTeX` §742
pub const SUPERSCRIPTSHIFTUP: i32 = 11;
/// `XeTeX` §742
pub const SUPERSCRIPTSHIFTUPCRAMPED: i32 = 12;
/// `XeTeX` §742
pub const SUPERSCRIPTBOTTOMMIN: i32 = 13;
/// `XeTeX` §742
pub const SUPERSCRIPTBASELINEDROPMAX: i32 = 14;
/// `XeTeX` §742
pub const SUBSUPERSCRIPTGAPMIN: i32 = 15;
/// `XeTeX` §742
pub const SUPERSCRIPTBOTTOMMAXWITHSUBSCRIPT: i32 = 16;
/// `XeTeX` §742
pub const SPACEAFTERSCRIPT: i32 = 17;
/// `XeTeX` §742
pub const UPPERLIMITGAPMIN: i32 = 18;
/// `XeTeX` §742
pub const UPPERLIMITBASELINERISEMIN: i32 = 19;
/// `XeTeX` §742
pub const LOWERLIMITGAPMIN: i32 = 20;
/// `XeTeX` §742
pub const LOWERLIMITBASELINEDROPMIN: i32 = 21;
/// `XeTeX` §742
pub const STACKTOPSHIFTUP: i32 = 22;
/// `XeTeX` §742
pub const STACKTOPDISPLAYSTYLESHIFTUP: i32 = 23;
/// `XeTeX` §742
pub const STACKBOTTOMSHIFTDOWN: i32 = 24;
/// `XeTeX` §742
pub const STACKBOTTOMDISPLAYSTYLESHIFTDOWN: i32 = 25;
/// `XeTeX` §742
pub const STACKGAPMIN: i32 = 26;
/// `XeTeX` §742
pub const STACKDISPLAYSTYLEGAPMIN: i32 = 27;
/// `XeTeX` §742
pub const STRETCHSTACKTOPSHIFTUP: i32 = 28;
/// `XeTeX` §742
pub const STRETCHSTACKBOTTOMSHIFTDOWN: i32 = 29;
/// `XeTeX` §742
pub const STRETCHSTACKGAPABOVEMIN: i32 = 30;
/// `XeTeX` §742
pub const STRETCHSTACKGAPBELOWMIN: i32 = 31;
/// `XeTeX` §742
pub const FRACTIONNUMERATORSHIFTUP: i32 = 32;
/// `XeTeX` §742
pub const FRACTIONNUMERATORDISPLAYSTYLESHIFTUP: i32 = 33;
/// `XeTeX` §742
pub const FRACTIONDENOMINATORSHIFTDOWN: i32 = 34;
/// `XeTeX` §742
pub const FRACTIONDENOMINATORDISPLAYSTYLESHIFTDOWN: i32 = 35;
/// `XeTeX` §742
pub const FRACTIONNUMERATORGAPMIN: i32 = 36;
/// `XeTeX` §742
pub const FRACTIONNUMDISPLAYSTYLEGAPMIN: i32 = 37;
/// `XeTeX` §742
pub const FRACTIONRULETHICKNESS: i32 = 38;
/// `XeTeX` §742
pub const FRACTIONDENOMINATORGAPMIN: i32 = 39;
/// `XeTeX` §742
pub const FRACTIONDENOMDISPLAYSTYLEGAPMIN: i32 = 40;
/// `XeTeX` §742
pub const SKEWEDFRACTIONHORIZONTALGAP: i32 = 41;
/// `XeTeX` §742
pub const SKEWEDFRACTIONVERTICALGAP: i32 = 42;
/// `XeTeX` §742
pub const OVERBARVERTICALGAP: i32 = 43;
/// `XeTeX` §742
pub const OVERBARRULETHICKNESS: i32 = 44;
/// `XeTeX` §742
pub const OVERBAREXTRAASCENDER: i32 = 45;
/// `XeTeX` §742
pub const UNDERBARVERTICALGAP: i32 = 46;
/// `XeTeX` §742
pub const UNDERBARRULETHICKNESS: i32 = 47;
/// `XeTeX` §742
pub const UNDERBAREXTRADESCENDER: i32 = 48;
/// `XeTeX` §742
pub const RADICALVERTICALGAP: i32 = 49;
/// `XeTeX` §742
pub const RADICALDISPLAYSTYLEVERTICALGAP: i32 = 50;
/// `XeTeX` §742
pub const RADICALRULETHICKNESS: i32 = 51;
/// `XeTeX` §742
pub const RADICALEXTRAASCENDER: i32 = 52;
/// `XeTeX` §742
pub const RADICALKERNBEFOREDEGREE: i32 = 53;
/// `XeTeX` §742
pub const RADICALKERNAFTERDEGREE: i32 = 54;
/// `XeTeX` §742
pub const LASTMATHVALUERECORD: i32 = RADICALKERNAFTERDEGREE;
/// `XeTeX` §742
pub const RADICALDEGREEBOTTOMRAISEPERCENT: i32 = 55;
/// `XeTeX` §742
pub const LASTMATHCONSTANT: i32 = RADICALDEGREEBOTTOMRAISEPERCENT;
/// `XeTeX` §804
pub const SUP_CMD: i32 = 0;
/// `XeTeX` §804
pub const SUB_CMD: i32 = 1;
/// `XeTeX` §1084
pub const PDFBOX_CROP: i32 = 1;
/// `XeTeX` §1084
pub const PDFBOX_MEDIA: i32 = 2;
/// `XeTeX` §1084
pub const PDFBOX_BLEED: i32 = 3;
/// `XeTeX` §1084
pub const PDFBOX_TRIM: i32 = 4;
/// `XeTeX` §1084
pub const PDFBOX_ART: i32 = 5;
/// `XeTeX` §1084
pub const PDFBOX_NONE: i32 = 6;
/// `XeTeX` §1276
pub const XETEX_MATH_CHAR_NUM_DEF_CODE: i32 = 8;
/// `XeTeX` §1276
pub const XETEX_MATH_CHAR_DEF_CODE: i32 = 9;
/// `XeTeX` §1398
pub const PIC_FILE_CODE: i32 = PDFTEX_LAST_EXTENSION_CODE + 1;
/// `XeTeX` §1398
pub const PDF_FILE_CODE: i32 = PDFTEX_LAST_EXTENSION_CODE + 2;
/// `XeTeX` §1398
pub const GLYPH_CODE: i32 = PDFTEX_LAST_EXTENSION_CODE + 3;
/// `XeTeX` §1398
pub const XETEX_INPUT_ENCODING_EXTENSION_CODE: i32 = PDFTEX_LAST_EXTENSION_CODE + 4;
/// `XeTeX` §1398
pub const XETEX_DEFAULT_ENCODING_EXTENSION_CODE: i32 = PDFTEX_LAST_EXTENSION_CODE + 5;
/// `XeTeX` §1398
pub const XETEX_LINEBREAK_LOCALE_EXTENSION_CODE: i32 = PDFTEX_LAST_EXTENSION_CODE + 6;

/// The bits of a character in a token (`XeTeX`'s 21; DESIGN 4.7).
pub const CHAR_BITS: u32 = 21;
/// The character bits of a character token.
pub const CHAR_MASK: i32 = MAX_CHAR_VAL - 1;

/// The token of character `chr` with command code `cmd` (§289).
#[inline]
#[must_use]
pub const fn char_token(cmd: i32, chr: i32) -> i32 {
    cmd * MAX_CHAR_VAL + chr
}

/// The command code of a character token (`t < CS_TOKEN_FLAG`).
#[inline]
#[must_use]
pub const fn tok_cmd(t: i32) -> i32 {
    t >> CHAR_BITS
}

/// The character of a character token (`t < CS_TOKEN_FLAG`): a tagged
/// digit's digit ([`TAG_BASE`]).
#[inline]
#[must_use]
pub const fn tok_chr(t: i32) -> i32 {
    let c = t & CHAR_MASK;
    if c >= TAG_BASE {
        b'0' as i32 + (c & 15)
    } else {
        c
    }
}

/// Relocatable numbers (DESIGN 4.1): a digit that `\the` or `\number`
/// made of a count register's value is a *tagged* token, a character
/// token of category 12 whose character code is past Unicode: from
/// `TAG_BASE`, the register's number (its *origin*) times 32, 16 on the
/// number's first digit, and the digit. [`tok_chr`] gives the digit, so
/// TeX reads a digit; what the job does with it decides whether the
/// number may be relocated (`reloc.rs`).
pub const TAG_BASE: i32 = 0x11_0000;
/// The origins a tag can name (registers `0..TAG_ORIGINS`).
pub const TAG_ORIGINS: i32 = (MAX_CHAR_VAL - TAG_BASE) >> 5;
/// The first tagged token.
pub const TAG_MIN_TOKEN: i32 = OTHER_TOKEN + TAG_BASE;
/// Past the last tagged token.
pub const TAG_END_TOKEN: i32 = OTHER_TOKEN + MAX_CHAR_VAL;

/// The tagged token of digit `digit` of a number of origin `origin`
/// (its first digit if `first`).
#[inline]
#[must_use]
pub const fn tagged_digit(origin: i32, first: bool, digit: i32) -> i32 {
    TAG_MIN_TOKEN + (origin << 5) + if first { 16 } else { 0 } + digit
}

/// Whether `t` is a tagged token.
#[inline]
#[must_use]
pub const fn is_tagged(t: i32) -> bool {
    t >= TAG_MIN_TOKEN && t < TAG_END_TOKEN
}

/// A tagged token's origin, first-digit flag and digit.
#[inline]
#[must_use]
pub const fn tag_of(t: i32) -> Option<(i32, bool, i32)> {
    if is_tagged(t) {
        let x = t - TAG_MIN_TOKEN;
        Some((x >> 5, x & 16 != 0, x & 15))
    } else {
        None
    }
}

/// `t` as TeX reads it: a tagged digit as the plain digit.
#[inline]
#[must_use]
pub const fn untag(t: i32) -> i32 {
    if is_tagged(t) {
        OTHER_TOKEN + tok_chr(t)
    } else {
        t
    }
}
