//! pdfencoding.c, pdfencoding.h: the encodings (`.enc` files and the PDF
//! predefined ones), their `/Encoding` resources and ToUnicode CMaps.
//!
//! The cache is `self.encoding.encodings`, indexed by `enc_id`.

use crate::prelude::*;

/// `FLAG_IS_PREDEFINED`.
pub const FLAG_IS_PREDEFINED: i32 = 1 << 0;
/// `FLAG_USED_BY_TYPE3`.
pub const FLAG_USED_BY_TYPE3: i32 = 1 << 1;
/// `CACHE_ALLOC_SIZE`.
pub const CACHE_ALLOC_SIZE: u32 = 16;
/// `WBUF_SIZE`.
pub const WBUF_SIZE: usize = 1024;

/// `pdf_encoding`.
#[derive(Clone, Debug)]
pub struct PdfEncoding {
    pub ident: Vec<u8>,
    pub enc_name: Vec<u8>,
    pub flags: i32,
    /// `.notdef` is `None`.
    pub glyphs: [Option<Vec<u8>>; 256],
    pub is_used: [u8; 256],
    pub tounicode: Option<Obj>,
    pub resource: Option<Obj>,
}

impl Default for PdfEncoding {
    fn default() -> Self {
        PdfEncoding {
            ident: Vec::new(),
            enc_name: Vec::new(),
            flags: 0,
            glyphs: core::array::from_fn(|_| None),
            is_used: [0; 256],
            tounicode: None,
            resource: None,
        }
    }
}

/// pdfencoding.c's statics: `enc_cache` (count = `encodings.len()`), and
/// `wbuf`, `range_min`, `range_max` (scratch for the ToUnicode CMaps).
#[derive(Clone, Debug, Default)]
pub struct State {
    /// `enc_cache.encodings`.
    pub encodings: Vec<PdfEncoding>,
    /// `enc_cache.capacity`.
    pub capacity: i32,
}

/// `pdf_init_encoding_struct`.
pub fn pdf_init_encoding_struct(encoding: &mut PdfEncoding) {
    todo!()
}

/// `glycmp` (static).
fn glycmp(v1: &[u8], v2: &[u8]) -> i32 {
    todo!()
}

/// `is_similar_charset` (static).
fn is_similar_charset(enc_vec: &[Option<Vec<u8>>], enc_vec2: &[&[u8]; 256]) -> bool {
    todo!()
}

impl Dpx {
    /// `create_encoding_resource` (static).
    fn create_encoding_resource(
        &mut self,
        enc_vec: &[Option<Vec<u8>>],
        baseenc_name: Option<&[u8]>,
        baseenc_vec: Option<&[&[u8]; 256]>,
        is_used: &[u8],
    ) -> Option<Obj> {
        todo!()
    }

    /// `pdf_flush_encoding` (static).
    fn pdf_flush_encoding(&mut self, enc_id: i32) {
        todo!()
    }

    /// `pdf_clean_encoding_struct` (static).
    fn pdf_clean_encoding_struct(&mut self, enc_id: i32) {
        todo!()
    }

    /// `make_encoding_differences` (static).
    fn make_encoding_differences(
        &mut self,
        enc_vec: &[Option<Vec<u8>>],
        baseenc: Option<&[&[u8]; 256]>,
        is_used: &[u8],
    ) -> Option<Obj> {
        todo!()
    }

    /// `load_encoding_file` (static): the enc_id, or -1.
    fn load_encoding_file(&mut self, filename: &[u8]) -> i32 {
        todo!()
    }

    /// `pdf_encoding_new_encoding` (static): the enc_id. `encoding_vec`
    /// holds 256 names (`.notdef` included as in the C tables).
    fn pdf_encoding_new_encoding(
        &mut self,
        enc_name: &[u8],
        ident: &[u8],
        encoding_vec: &[Option<Vec<u8>>],
        flags: i32,
    ) -> i32 {
        todo!()
    }

    /// `pdf_init_encodings`.
    pub fn pdf_init_encodings(&mut self) {
        todo!()
    }

    /// `pdf_encoding_complete`.
    pub fn pdf_encoding_complete(&mut self) {
        todo!()
    }

    /// `pdf_close_encodings`.
    pub fn pdf_close_encodings(&mut self) {
        todo!()
    }

    /// `pdf_encoding_findresource`: the enc_id, or -1.
    pub fn pdf_encoding_findresource(&mut self, enc_name: &[u8]) -> i32 {
        todo!()
    }

    /// `pdf_encoding_get_encoding`: a copy of the 256 glyph names
    /// (`None` = `.notdef`).
    pub fn pdf_encoding_get_encoding(&mut self, enc_id: i32) -> Vec<Option<Vec<u8>>> {
        todo!()
    }

    /// `pdf_get_encoding_obj`: the `/Encoding` resource (not linked).
    pub fn pdf_get_encoding_obj(&mut self, enc_id: i32) -> Option<Obj> {
        todo!()
    }

    /// `pdf_encoding_is_predefined`.
    pub fn pdf_encoding_is_predefined(&mut self, enc_id: i32) -> bool {
        todo!()
    }

    /// `pdf_encoding_used_by_type3`.
    pub fn pdf_encoding_used_by_type3(&mut self, enc_id: i32) {
        todo!()
    }

    /// `pdf_encoding_get_name`: a copy.
    pub fn pdf_encoding_get_name(&mut self, enc_id: i32) -> Vec<u8> {
        todo!()
    }

    /// `pdf_encoding_add_usedchars`: ORs `is_used` (256 bytes) into the
    /// encoding's.
    pub fn pdf_encoding_add_usedchars(&mut self, encoding_id: i32, is_used: &[u8]) {
        todo!()
    }

    /// `pdf_encoding_get_tounicode` (not linked).
    pub fn pdf_encoding_get_tounicode(&mut self, encoding_id: i32) -> Option<Obj> {
        todo!()
    }

    /// `pdf_create_ToUnicode_CMap`: a stream object (not a reference).
    /// `is_used` is none for all 256 codes.
    #[allow(non_snake_case)]
    pub fn pdf_create_ToUnicode_CMap(
        &mut self,
        enc_name: &[u8],
        enc_vec: &[Option<Vec<u8>>],
        is_used: Option<&[u8]>,
    ) -> Option<Obj> {
        todo!()
    }

    /// `pdf_load_ToUnicode_stream`: the CMap `ident` as a stream (not a
    /// reference).
    #[allow(non_snake_case)]
    pub fn pdf_load_ToUnicode_stream(&mut self, ident: &[u8]) -> Option<Obj> {
        todo!()
    }
}

/// `MacRomanEncoding`.
pub static MAC_ROMAN_ENCODING: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b".notdef",
    b"Adieresis",
    b"Aring",
    b"Ccedilla",
    b"Eacute",
    b"Ntilde",
    b"Odieresis",
    b"Udieresis",
    b"aacute",
    b"agrave",
    b"acircumflex",
    b"adieresis",
    b"atilde",
    b"aring",
    b"ccedilla",
    b"eacute",
    b"egrave",
    b"ecircumflex",
    b"edieresis",
    b"iacute",
    b"igrave",
    b"icircumflex",
    b"idieresis",
    b"ntilde",
    b"oacute",
    b"ograve",
    b"ocircumflex",
    b"odieresis",
    b"otilde",
    b"uacute",
    b"ugrave",
    b"ucircumflex",
    b"udieresis",
    b"dagger",
    b"degree",
    b"cent",
    b"sterling",
    b"section",
    b"bullet",
    b"paragraph",
    b"germandbls",
    b"registered",
    b"copyright",
    b"trademark",
    b"acute",
    b"dieresis",
    b"notequal",
    b"AE",
    b"Oslash",
    b"infinity",
    b"plusminus",
    b"lessequal",
    b"greaterequal",
    b"yen",
    b"mu",
    b"partialdiff",
    b"summation",
    b"product",
    b"pi",
    b"integral",
    b"ordfeminine",
    b"ordmasculine",
    b"Omega",
    b"ae",
    b"oslash",
    b"questiondown",
    b"exclamdown",
    b"logicalnot",
    b"radical",
    b"florin",
    b"approxequal",
    b"Delta",
    b"guillemotleft",
    b"guillemotright",
    b"ellipsis",
    b"space",
    b"Agrave",
    b"Atilde",
    b"Otilde",
    b"OE",
    b"oe",
    b"endash",
    b"emdash",
    b"quotedblleft",
    b"quotedblright",
    b"quoteleft",
    b"quoteright",
    b"divide",
    b"lozenge",
    b"ydieresis",
    b"Ydieresis",
    b"fraction",
    b"currency",
    b"guilsinglleft",
    b"guilsinglright",
    b"fi",
    b"fl",
    b"daggerdbl",
    b"periodcentered",
    b"quotesinglbase",
    b"quotedblbase",
    b"perthousand",
    b"Acircumflex",
    b"Ecircumflex",
    b"Aacute",
    b"Edieresis",
    b"Egrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Igrave",
    b"Oacute",
    b"Ocircumflex",
    b"apple",
    b"Ograve",
    b"Uacute",
    b"Ucircumflex",
    b"Ugrave",
    b"dotlessi",
    b"circumflex",
    b"tilde",
    b"macron",
    b"breve",
    b"dotaccent",
    b"ring",
    b"cedilla",
    b"hungarumlaut",
    b"ogonek",
    b"caron",
];

/// `MacExpertEncoding`.
pub static MAC_EXPERT_ENCODING: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclamsmall",
    b"Hungarumlautsmall",
    b"centoldstyle",
    b"dollaroldstyle",
    b"dollarsuperior",
    b"ampersandsmall",
    b"Acutesmall",
    b"parenleftsuperior",
    b"parenrightsuperior",
    b"twodotenleader",
    b"onedotenleader",
    b"comma",
    b"hyphen",
    b"period",
    b"fraction",
    b"zerooldstyle",
    b"oneoldstyle",
    b"twooldstyle",
    b"threeoldstyle",
    b"fouroldstyle",
    b"fiveoldstyle",
    b"sixoldstyle",
    b"sevenoldstyle",
    b"eightoldstyle",
    b"nineoldstyle",
    b"colon",
    b"semicolon",
    b".notdef",
    b"threequartersemdash",
    b".notdef",
    b"questionsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Ethsmall",
    b".notdef",
    b".notdef",
    b"onequarter",
    b"onehalf",
    b"threequarters",
    b"oneeighth",
    b"threeeighths",
    b"fiveeighths",
    b"seveneighths",
    b"onethird",
    b"twothirds",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ff",
    b"fi",
    b"fl",
    b"ffi",
    b"ffl",
    b"parenleftinferior",
    b".notdef",
    b"parenrightinferior",
    b"Circumflexsmall",
    b"hypheninferior",
    b"Gravesmall",
    b"Asmall",
    b"Bsmall",
    b"Csmall",
    b"Dsmall",
    b"Esmall",
    b"Fsmall",
    b"Gsmall",
    b"Hsmall",
    b"Ismall",
    b"Jsmall",
    b"Ksmall",
    b"Lsmall",
    b"Msmall",
    b"Nsmall",
    b"Osmall",
    b"Psmall",
    b"Qsmall",
    b"Rsmall",
    b"Ssmall",
    b"Tsmall",
    b"Usmall",
    b"Vsmall",
    b"Wsmall",
    b"Xsmall",
    b"Ysmall",
    b"Zsmall",
    b"colonmonetary",
    b"onefitted",
    b"rupiah",
    b"Tildesmall",
    b".notdef",
    b".notdef",
    b"asuperior",
    b"centsuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Aacutesmall",
    b"Agravesmall",
    b"Acircumflexsmall",
    b"Adieresissmall",
    b"Atildesmall",
    b"Aringsmall",
    b"Ccedillasmall",
    b"Eacutesmall",
    b"Egravesmall",
    b"Ecircumflexsmall",
    b"Edieresissmall",
    b"Iacutesmall",
    b"Igravesmall",
    b"Icircumflexsmall",
    b"Idieresissmall",
    b"Ntildesmall",
    b"Oacutesmall",
    b"Ogravesmall",
    b"Ocircumflexsmall",
    b"Odieresissmall",
    b"Otildesmall",
    b"Uacutesmall",
    b"Ugravesmall",
    b"Ucircumflexsmall",
    b"Udieresissmall",
    b".notdef",
    b"eightsuperior",
    b"fourinferior",
    b"threeinferior",
    b"sixinferior",
    b"eightinferior",
    b"seveninferior",
    b"Scaronsmall",
    b".notdef",
    b"centinferior",
    b"twoinferior",
    b".notdef",
    b"Dieresissmall",
    b".notdef",
    b"Caronsmall",
    b"osuperior",
    b"fiveinferior",
    b".notdef",
    b"commainferior",
    b"periodinferior",
    b"Yacutesmall",
    b".notdef",
    b"dollarinferior",
    b".notdef",
    b".notdef",
    b"Thornsmall",
    b".notdef",
    b"nineinferior",
    b"zeroinferior",
    b"Zcaronsmall",
    b"AEsmall",
    b"Oslashsmall",
    b"questiondownsmall",
    b"oneinferior",
    b"Lslashsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Cedillasmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"OEsmall",
    b"figuredash",
    b"hyphensuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"exclamdownsmall",
    b".notdef",
    b"Ydieresissmall",
    b".notdef",
    b"onesuperior",
    b"twosuperior",
    b"threesuperior",
    b"foursuperior",
    b"fivesuperior",
    b"sixsuperior",
    b"sevensuperior",
    b"ninesuperior",
    b"zerosuperior",
    b".notdef",
    b"esuperior",
    b"rsuperior",
    b"tsuperior",
    b".notdef",
    b".notdef",
    b"isuperior",
    b"ssuperior",
    b"dsuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"lsuperior",
    b"Ogoneksmall",
    b"Brevesmall",
    b"Macronsmall",
    b"bsuperior",
    b"nsuperior",
    b"msuperior",
    b"commasuperior",
    b"periodsuperior",
    b"Dotaccentsmall",
    b"Ringsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
];

/// `WinAnsiEncoding`.
pub static WIN_ANSI_ENCODING: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b"bullet",
    b"Euro",
    b"bullet",
    b"quotesinglbase",
    b"florin",
    b"quotedblbase",
    b"ellipsis",
    b"dagger",
    b"daggerdbl",
    b"circumflex",
    b"perthousand",
    b"Scaron",
    b"guilsinglleft",
    b"OE",
    b"bullet",
    b"Zcaron",
    b"bullet",
    b"bullet",
    b"quoteleft",
    b"quoteright",
    b"quotedblleft",
    b"quotedblright",
    b"bullet",
    b"endash",
    b"emdash",
    b"tilde",
    b"trademark",
    b"scaron",
    b"guilsinglright",
    b"oe",
    b"bullet",
    b"zcaron",
    b"Ydieresis",
    b"space",
    b"exclamdown",
    b"cent",
    b"sterling",
    b"currency",
    b"yen",
    b"brokenbar",
    b"section",
    b"dieresis",
    b"copyright",
    b"ordfeminine",
    b"guillemotleft",
    b"logicalnot",
    b"hyphen",
    b"registered",
    b"macron",
    b"degree",
    b"plusminus",
    b"twosuperior",
    b"threesuperior",
    b"acute",
    b"mu",
    b"paragraph",
    b"periodcentered",
    b"cedilla",
    b"onesuperior",
    b"ordmasculine",
    b"guillemotright",
    b"onequarter",
    b"onehalf",
    b"threequarters",
    b"questiondown",
    b"Agrave",
    b"Aacute",
    b"Acircumflex",
    b"Atilde",
    b"Adieresis",
    b"Aring",
    b"AE",
    b"Ccedilla",
    b"Egrave",
    b"Eacute",
    b"Ecircumflex",
    b"Edieresis",
    b"Igrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Eth",
    b"Ntilde",
    b"Ograve",
    b"Oacute",
    b"Ocircumflex",
    b"Otilde",
    b"Odieresis",
    b"multiply",
    b"Oslash",
    b"Ugrave",
    b"Uacute",
    b"Ucircumflex",
    b"Udieresis",
    b"Yacute",
    b"Thorn",
    b"germandbls",
    b"agrave",
    b"aacute",
    b"acircumflex",
    b"atilde",
    b"adieresis",
    b"aring",
    b"ae",
    b"ccedilla",
    b"egrave",
    b"eacute",
    b"ecircumflex",
    b"edieresis",
    b"igrave",
    b"iacute",
    b"icircumflex",
    b"idieresis",
    b"eth",
    b"ntilde",
    b"ograve",
    b"oacute",
    b"ocircumflex",
    b"otilde",
    b"odieresis",
    b"divide",
    b"oslash",
    b"ugrave",
    b"uacute",
    b"ucircumflex",
    b"udieresis",
    b"yacute",
    b"thorn",
    b"ydieresis",
];
