//! tt_post.c, tt_post.h: the `post` table (glyph names).

use crate::prelude::*;
use crate::sfnt::{FWord, Fixed, Sfnt, ULONG, USHORT};

/// `NAME_STR_OFFSET`: offset from the beginning of the post table.
pub const NAME_STR_OFFSET: u32 = 32;

/// `struct tt_post_table`.
#[derive(Clone, Debug, Default)]
pub struct TtPostTable {
    /// C's `Version`.
    pub version: Fixed,
    pub italic_angle: Fixed,
    pub underline_position: FWord,
    pub underline_thickness: FWord,
    pub is_fixed_pitch: ULONG,
    pub min_mem_type42: ULONG,
    pub max_mem_type42: ULONG,
    pub min_mem_type1: ULONG,
    pub max_mem_type1: ULONG,
    pub number_of_glyphs: USHORT,
    /// `glyphNamePtr`: the name of each glyph (copies of the
    /// `MACGLYPHORDER` entry or of `names[i]` C pointed to), empty when C's
    /// is NULL.
    pub glyph_name_ptr: Vec<Option<Vec<u8>>>,
    /// Non-standard glyph names.
    pub names: Vec<Vec<u8>>,
    /// Number of glyph names in `names`.
    pub count: USHORT,
}

/// `read_v2_post_names` (static): 0, or -1 for an invalid table.
fn read_v2_post_names(post: &mut TtPostTable, sfont: &mut Sfnt) -> i32 {
    todo!()
}

impl Sfnt {
    /// `tt_read_post_table`: none for an invalid version 2.0 table
    /// (`sfnt_locate_table` ERRORs without one).
    pub fn tt_read_post_table(&mut self) -> Option<TtPostTable> {
        todo!()
    }
}

impl TtPostTable {
    /// `tt_release_post_table`.
    pub fn tt_release_post_table(self) {}
    /// `tt_lookup_post_table`: the gid, 0 if not found.
    #[must_use]
    pub fn tt_lookup_post_table(&self, glyphname: &[u8]) -> USHORT {
        todo!()
    }
    /// `tt_get_glyphname`: a copy.
    #[must_use]
    pub fn tt_get_glyphname(&self, gid: USHORT) -> Option<Vec<u8>> {
        todo!()
    }
}

/// `macglyphorder`: the Macintosh glyph order (Apple's TTRefMan).
pub static MACGLYPHORDER: [&[u8]; 258] = [
    b".notdef",
    b".null",
    b"nonmarkingreturn",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b"Adieresis",
    b"Aring",
    b"Ccedilla",
    b"Eacute",
    b"Ntilde",
    b"Odieresis",
    b"Udieresis",
    b"aacute",
    b"agrave",
    b"acircumflex",
    b"adieresis",
    b"atilde",
    b"aring",
    b"ccedilla",
    b"eacute",
    b"egrave",
    b"ecircumflex",
    b"edieresis",
    b"iacute",
    b"igrave",
    b"icircumflex",
    b"idieresis",
    b"ntilde",
    b"oacute",
    b"ograve",
    b"ocircumflex",
    b"odieresis",
    b"otilde",
    b"uacute",
    b"ugrave",
    b"ucircumflex",
    b"udieresis",
    b"dagger",
    b"degree",
    b"cent",
    b"sterling",
    b"section",
    b"bullet",
    b"paragraph",
    b"germandbls",
    b"registered",
    b"copyright",
    b"trademark",
    b"acute",
    b"dieresis",
    b"notequal",
    b"AE",
    b"Oslash",
    b"infinity",
    b"plusminus",
    b"lessequal",
    b"greaterequal",
    b"yen",
    b"mu",
    b"partialdiff",
    b"summation",
    b"product",
    b"pi",
    b"integral",
    b"ordfeminine",
    b"ordmasculine",
    b"Omega",
    b"ae",
    b"oslash",
    b"questiondown",
    b"exclamdown",
    b"logicalnot",
    b"radical",
    b"florin",
    b"approxequal",
    b"Delta",
    b"guillemotleft",
    b"guillemotright",
    b"ellipsis",
    b"nonbreakingspace",
    b"Agrave",
    b"Atilde",
    b"Otilde",
    b"OE",
    b"oe",
    b"endash",
    b"emdash",
    b"quotedblleft",
    b"quotedblright",
    b"quoteleft",
    b"quoteright",
    b"divide",
    b"lozenge",
    b"ydieresis",
    b"Ydieresis",
    b"fraction",
    b"currency",
    b"guilsinglleft",
    b"guilsinglright",
    b"fi",
    b"fl",
    b"daggerdbl",
    b"periodcentered",
    b"quotesinglbase",
    b"quotedblbase",
    b"perthousand",
    b"Acircumflex",
    b"Ecircumflex",
    b"Aacute",
    b"Edieresis",
    b"Egrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Igrave",
    b"Oacute",
    b"Ocircumflex",
    b"apple",
    b"Ograve",
    b"Uacute",
    b"Ucircumflex",
    b"Ugrave",
    b"dotlessi",
    b"circumflex",
    b"tilde",
    b"macron",
    b"breve",
    b"dotaccent",
    b"ring",
    b"cedilla",
    b"hungarumlaut",
    b"ogonek",
    b"caron",
    b"Lslash",
    b"lslash",
    b"Scaron",
    b"scaron",
    b"Zcaron",
    b"zcaron",
    b"brokenbar",
    b"Eth",
    b"eth",
    b"Yacute",
    b"yacute",
    b"Thorn",
    b"thorn",
    b"minus",
    b"multiply",
    b"onesuperior",
    b"twosuperior",
    b"threesuperior",
    b"onehalf",
    b"onequarter",
    b"threequarters",
    b"franc",
    b"Gbreve",
    b"gbreve",
    b"Idotaccent",
    b"Scedilla",
    b"scedilla",
    b"Cacute",
    b"cacute",
    b"Ccaron",
    b"ccaron",
    b"dcroat",
];
