#!/usr/bin/env python3
"""Generate crates/partex-engine/src/web.rs: every numeric constant (`@d x=...`
or an arithmetic `@d x==...`) of the merged pdfTeX WEB source (a superset of
tex.web's), in source order. Names that tex.web also defines cite its section
(`§N`); pdfTeX's own cite `pdfTeX §N`.

Run after scripts/merge-web.sh:  python3 scripts/gen-webconsts.py
"""
import re, pathlib

root = pathlib.Path(__file__).resolve().parent.parent
ID = r"[A-Za-z_][A-Za-z_0-9]*"


def parse(file):
    web = (root / "target/web" / file).read_text(errors="replace").split("\n")
    sec = 0
    defs, order = {}, []
    for line in web:
        if re.match(r"^@( |\*|$|\t)", line):
            sec += 1
        m = re.match(rf"^(?:@ )?@d\s+({ID})\s*(==|=)\s*(.*)$", line)
        if not m:
            continue
        name, _, rest = m.groups()
        rhs = rest.split("{")[0].strip().rstrip(";").strip()
        rhs = re.sub(r"@[;!/|#,t>\\]", "", rhs).strip()
        if not rhs or "#" in rhs or re.search(r'(?<!@)"[^"]{2,}"', rhs) or re.search(r"@(?![\'\"])", rhs):
            continue
        if not re.fullmatch(r"[A-Za-z_0-9@'\"\s+\-*()]*(div [A-Za-z_0-9@'\"()]+)?", rhs):
            continue
        if name not in defs:
            defs[name] = (sec, rhs)
            order.append(name)
    return defs, order


defs, order = parse("pdftex-merged.web")
tex_defs, _ = parse("tex-merged.web")

def ids(rhs):
    rhs = re.sub(r'@"[0-9A-F]+|"."', "", rhs)
    return set(re.findall(rf"\b{ID}\b", rhs)) - {"div"}

known = set(defs)
changed = True
while changed:
    changed = False
    for n in list(known):
        if not ids(defs[n][1]) <= known:
            known.discard(n)
            changed = True

def conv(v):
    # WEB single-character strings denote character codes; `""""` is `"`.
    v = v.replace('""""', "34")
    v = re.sub(r'"(.)"', lambda m: str(ord(m.group(1))), v)
    v = re.sub(r"@'([0-7]+)", lambda m: "0o" + m.group(1), v)
    v = re.sub(r'@"([0-9A-F]+)', lambda m: "0x" + m.group(1), v)
    v = re.sub(r"\bdiv\b", "/", v)
    v = re.sub(r"\b0x[0-9A-F]+\b", lambda m: m.group(0).lower(), v)
    return re.sub(rf"\b(?!0x){ID}\b", lambda m: m.group(0).upper(), v)

out = [
    "//! Every numeric constant of the merged WEB source (`@d x=...`), in source",
    "//! order. Generated by `scripts/gen-webconsts.py`; do not edit by hand.",
    "//! The section comments are where tex.web (or else pdftex.web) defines each",
    "//! name; values are pdfTeX's, whose layout is a superset of TeX's.",
    "",
    "#![allow(dead_code, clippy::identity_op, clippy::eq_op, clippy::double_parens)]",
    "",
]
for n in order:
    if n in known:
        sec, rhs = defs[n]
        cite = f"§{tex_defs[n][0]}" if n in tex_defs else f"pdfTeX §{sec}"
        out.append(f"/// {cite}")
        out.append(f"pub const {n.upper()}: i32 = {conv(rhs)};")
(root / "crates/partex-engine/src/web.rs").write_text("\n".join(out) + "\n")
print(f"{len(known)} constants")
