#!/usr/bin/env python3
"""Generates src/xetex/ot_lang.rs from HarfBuzz's hb-ot-tag-table.hh:
hb_ot_tag_to_language's answer for every OpenType language tag the tables
know (the ambiguous tags' disambiguation first, then the first entry of
ot_languages2, ot_languages3 and ot_languages3_multi, in that order).

    scripts/sandbox python3 crates/partex-otf/tools/gen-ot-lang.py \
        upstream/harfbuzz/src/hb-ot-tag-table.hh > crates/partex-otf/src/xetex/ot_lang.rs
"""
import re, sys

src = open(sys.argv[1], encoding='utf-8').read()
TAG = r"HB_TAG\('(.)','(.)','(.)','(.)'\)"

def tagv(m):
    return int.from_bytes(''.join(m).encode('latin-1'), 'big')

def section(name, end='};'):
    i = src.index(name)
    return src[i:src.index(end, i)]

answer = {}
order = []
def put(t, lang):
    if t not in answer:
        answer[t] = lang
        order.append(t)

amb = section('hb_ot_ambiguous_tag_to_language (hb_tag_t tag)\n{', '\n}\n')
for m in re.finditer(r"case " + TAG + r":.*?\n\s*return hb_language_from_string \(\"([^\"]*)\"", amb):
    put(tagv(m.groups()[:4]), m.group(5))

def langstr(groups, n):
    return ''.join(groups)[:n]

for m in re.finditer(r"\{" + TAG + r",\s*" + TAG + r"\}", section('ot_languages2[] = {')):
    g = m.groups()
    put(tagv(g[4:8]), langstr(g[0:4], 2))
for m in re.finditer(r"\{" + TAG + r",\s*" + TAG + r"\}", section('ot_languages3[] = {')):
    g = m.groups()
    put(tagv(g[4:8]), langstr(g[0:4], 3))
values = [tagv(m.groups()) for m in re.finditer(TAG, section('ot_languages3_multi_values[] = {'))]
for m in re.finditer(r"\{" + TAG + r",\s*(\d+),\s*(\d+)\}", section('ot_languages3_multi[] = {')):
    g = m.groups()
    off, cnt = int(g[4]), int(g[5])
    for t in values[off:off + cnt]:
        put(t, langstr(g[0:4], 3))

print("// Generated by tools/gen-ot-lang.py from HarfBuzz 14.5.0's hb-ot-tag-table.hh;")
print("// do not edit.")
print("//! `hb_ot_tag_to_language`'s table: OpenType language tag -> BCP 47.")
print()
print("/// (tag, language), sorted by tag.")
print("pub(super) static OT_TAG_TO_LANGUAGE: &[(u32, &str)] = &[")
for t in sorted(answer):
    print(f"    (0x{t:08x}, {answer[t]!r}),".replace("'", '"'))
print("];")
